// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';

export function AddCoin(arg1:string,arg2:storage.Coin):Promise<string>;

export function DeleteCoin(arg1:string,arg2:string):Promise<void>;

export function DeleteVault(arg1:string):Promise<void>;

export function GetCoins(arg1:string):Promise<Array<storage.Coin>>;

export function GetVault(arg1:string):Promise<storage.Vault>;

export function GetVaults():Promise<Array<storage.Vault>>;

export function SaveCoin(arg1:string,arg2:storage.Coin):Promise<void>;

export function SaveVault(arg1:storage.Vault):Promise<string>;
