// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCoin(arg1, arg2) {
  return window['go']['storage']['Store']['AddCoin'](arg1, arg2);
}

export function DeleteCoin(arg1, arg2) {
  return window['go']['storage']['Store']['DeleteCoin'](arg1, arg2);
}

export function DeleteVault(arg1) {
  return window['go']['storage']['Store']['DeleteVault'](arg1);
}

export function GetCoins(arg1) {
  return window['go']['storage']['Store']['GetCoins'](arg1);
}

export function GetVault(arg1) {
  return window['go']['storage']['Store']['GetVault'](arg1);
}

export function GetVaults() {
  return window['go']['storage']['Store']['GetVaults']();
}

export function SaveCoin(arg1, arg2) {
  return window['go']['storage']['Store']['SaveCoin'](arg1, arg2);
}

export function SaveVault(arg1) {
  return window['go']['storage']['Store']['SaveVault'](arg1);
}
