export enum StorageKey {
  vaults = 'vaults',
  fiatCurrency = 'fiatCurrency',
  currentVaultId = 'currentVaultId',
  vaultsCoins = 'vaultsCoins',
  defaultChains = 'defaultChains',
  vaultFolders = 'vaultFolders',
  addressBookItems = 'addressBookItems',
  language = 'language',
  isBalanceVisible = 'isVaultBalanceVisible',
  isBlockaidEnabled = 'isBlockaidEnabled',
  hasFinishedOnboarding = 'hasFinishedOnboarding',
  coinFinderIgnore = 'coinFinderIgnore',
  passcodeEncryption = 'passcodeEncryption',
  passcodeAutoLock = 'passcodeAutoLock',
  hasFinishedReferralsOnboarding = 'hasFinishedReferralsOnboarding',
  hasAddedFriendReferral = 'hasAddedFriendReferral',
  appSessions = 'appSessions',
  latestInstalledVersion = 'latestInstalledVersion',
}
