import { Chain } from '../../model/chain';

export const feeUnitRecord: Record<Chain, string> = {
  [Chain.THORChain]: 'RUNE',
  [Chain.Solana]: 'SOL',
  [Chain.Ethereum]: 'Gwei',
  [Chain.Avalanche]: 'Gwei',
  [Chain.Base]: 'Gwei',
  [Chain.Blast]: 'Gwei',
  [Chain.Arbitrum]: 'Gwei',
  [Chain.Polygon]: 'Gwei',
  [Chain.Optimism]: 'Gwei',
  [Chain.BSC]: 'Gwei',
  [Chain.CronosChain]: 'Gwei',
  [Chain.Zksync]: 'Gwei',
  [Chain.Bitcoin]: 'BTC/vbyte',
  [Chain.BitcoinCash]: 'BCH/vbyte',
  [Chain.Litecoin]: 'LTC/vbyte',
  [Chain.Dogecoin]: 'DOGE/vbyte',
  [Chain.Dash]: 'DASH/vbyte',
  [Chain.Cosmos]: 'uatom',
  [Chain.Kujira]: 'ukuji',
  [Chain.MayaChain]: 'CACAO',
  [Chain.Sui]: 'SUI',
  [Chain.Polkadot]: 'DOT',
  [Chain.Dydx]: 'adydx',
};
