nodeLinker: node-modules

npmPreapprovedPackages:
  - "@vultisig/core-chain@2.25.1"
  - "@vultisig/core-mpc@1.11.0"
  - "@vultisig/lib-utils@0.10.4"
  - "@vultisig/sdk@2.19.19"

yarnPath: .yarn/releases/yarn-4.16.0.cjs
