nodeLinker: node-modules

npmPreapprovedPackages:
  - "@vultisig/core-chain@2.38.0"
  - "@vultisig/core-mpc@1.20.2"
  - "@vultisig/lib-utils@0.10.5"
  - "@vultisig/mpc-wasm@0.1.7"
  - "@vultisig/sdk@5.0.0"

yarnPath: .yarn/releases/yarn-4.16.0.cjs
