nodeLinker: node-modules

npmPreapprovedPackages:
  - "@vultisig/core-chain@2.27.0"
  - "@vultisig/core-mpc@1.12.1"
  - "@vultisig/lib-utils@0.10.4"
  - "@vultisig/mpc-wasm@0.1.6"
  - "@vultisig/sdk@2.21.0"

yarnPath: .yarn/releases/yarn-4.16.0.cjs
