import { describe, expect, it, vi } from 'vitest';

import * as utils from '../../../../utils/util';
import { generateServiceName } from '.';

describe('generateServiceName', () => {
  it('should return a string that starts with "Vultisig-Windows-"', () => {
    const serviceName = generateServiceName();
    expect(typeof serviceName).toBe('string');
    expect(serviceName.startsWith('Vultisig-Windows-')).toBe(true);
  });

  it('should include a number generated by generateRandomNumber', () => {
    const spy = vi.spyOn(utils, 'generateRandomNumber').mockReturnValue(12345);
    const serviceName = generateServiceName();
    expect(spy).toHaveBeenCalled();
    expect(serviceName).toBe('Vultisig-Windows-12345');
    spy.mockRestore();
  });
});
