import { Chain } from '../../model/chain';

export const hasMultipleCoinsSupport: Record<Chain, boolean> = {
  [Chain.THORChain]: true,
  [Chain.MayaChain]: true,
  [Chain.Arbitrum]: true,
  [Chain.Avalanche]: true,
  [Chain.Base]: true,
  [Chain.CronosChain]: true,
  [Chain.Sui]: true,
  [Chain.BSC]: true,
  [Chain.Blast]: true,
  [Chain.Ethereum]: true,
  [Chain.Optimism]: true,
  [Chain.Polygon]: true,
  [Chain.Bitcoin]: false,
  [Chain.BitcoinCash]: false,
  [Chain.Litecoin]: false,
  [Chain.Dogecoin]: false,
  [Chain.Dash]: false,
  [Chain.Solana]: true,
  [Chain.Gaia]: true,
  [Chain.Kujira]: true,
  [Chain.Dydx]: true,
  [Chain.Polkadot]: true,
  [Chain.ZkSync]: true,
};
