import { Chain } from '../model/chain';
import { CoinMeta } from '../model/coin-meta';

export const chainFeeCoin: Record<Chain, CoinMeta> = {
  [Chain.Bitcoin]: {
    chain: Chain.Bitcoin,
    ticker: 'BTC',
    logo: 'btc',
    decimals: 8,
    priceProviderId: 'bitcoin',
    contractAddress: '',
    isNativeToken: true,
  },
  [Chain.BitcoinCash]: {
    chain: Chain.BitcoinCash,
    ticker: 'BCH',
    logo: 'bch',
    decimals: 8,
    priceProviderId: 'bitcoin-cash',
    contractAddress: '',
    isNativeToken: true,
  },
  [Chain.Litecoin]: {
    chain: Chain.Litecoin,
    ticker: 'LTC',
    logo: 'ltc',
    decimals: 8,
    priceProviderId: 'litecoin',
    contractAddress: '',
    isNativeToken: true,
  },
  [Chain.Dogecoin]: {
    chain: Chain.Dogecoin,
    ticker: 'DOGE',
    logo: 'doge',
    decimals: 8,
    priceProviderId: 'dogecoin',
    contractAddress: '',
    isNativeToken: true,
  },
  [Chain.Dash]: {
    chain: Chain.Dash,
    ticker: 'DASH',
    logo: 'dash',
    decimals: 8,
    priceProviderId: 'dash',
    contractAddress: '',
    isNativeToken: true,
  },
  [Chain.Ripple]: {
    chain: Chain.Ripple,
    ticker: 'XRP',
    logo: 'xrp',
    decimals: 6,
    priceProviderId: 'ripple',
    contractAddress: '',
    isNativeToken: true,
  },
  [Chain.THORChain]: {
    chain: Chain.THORChain,
    ticker: 'RUNE',
    logo: 'rune',
    decimals: 8,
    priceProviderId: 'thorchain',
    contractAddress: '',
    isNativeToken: true,
  },
  [Chain.MayaChain]: {
    chain: Chain.MayaChain,
    ticker: 'CACAO',
    logo: 'cacao',
    decimals: 10,
    priceProviderId: 'cacao',
    contractAddress: '',
    isNativeToken: true,
  },
  [Chain.Solana]: {
    chain: Chain.Solana,
    ticker: 'SOL',
    logo: 'solana',
    decimals: 9,
    priceProviderId: 'solana',
    contractAddress: '',
    isNativeToken: true,
  },
  [Chain.Ton]: {
    chain: Chain.Ton,
    ticker: 'TON',
    logo: 'ton',
    decimals: 9,
    priceProviderId: 'the-open-network',
    contractAddress: '',
    isNativeToken: true,
  },
  [Chain.Ethereum]: {
    chain: Chain.Ethereum,
    ticker: 'ETH',
    logo: 'eth',
    decimals: 18,
    priceProviderId: 'ethereum',
    contractAddress: '',
    isNativeToken: true,
  },
  [Chain.Avalanche]: {
    chain: Chain.Avalanche,
    ticker: 'AVAX',
    logo: 'avax',
    decimals: 18,
    priceProviderId: 'avalanche-2',
    contractAddress: '',
    isNativeToken: true,
  },
  [Chain.BSC]: {
    chain: Chain.BSC,
    ticker: 'BNB',
    logo: 'bsc',
    decimals: 18,
    priceProviderId: 'binancecoin',
    contractAddress: '',
    isNativeToken: true,
  },
  [Chain.Base]: {
    chain: Chain.Base,
    ticker: 'ETH',
    logo: 'base',
    decimals: 18,
    priceProviderId: 'ethereum',
    contractAddress: '',
    isNativeToken: true,
  },
  [Chain.Arbitrum]: {
    chain: Chain.Arbitrum,
    ticker: 'ETH',
    logo: 'arbitrum',
    decimals: 18,
    priceProviderId: 'ethereum',
    contractAddress: '',
    isNativeToken: true,
  },
  [Chain.Optimism]: {
    chain: Chain.Optimism,
    ticker: 'ETH',
    logo: 'optimism',
    decimals: 18,
    priceProviderId: 'ethereum',
    contractAddress: '',
    isNativeToken: true,
  },
  [Chain.Polygon]: {
    chain: Chain.Polygon,
    ticker: 'MATIC',
    logo: 'matic',
    decimals: 18,
    priceProviderId: 'matic-network',
    contractAddress: '',
    isNativeToken: true,
  },
  [Chain.Blast]: {
    chain: Chain.Blast,
    ticker: 'ETH',
    logo: 'blast',
    decimals: 18,
    priceProviderId: 'ethereum',
    contractAddress: '',
    isNativeToken: true,
  },
  [Chain.CronosChain]: {
    chain: Chain.CronosChain,
    ticker: 'CRO',
    logo: 'cro',
    decimals: 18,
    priceProviderId: 'crypto-com-chain',
    contractAddress: '',
    isNativeToken: true,
  },
  [Chain.Zksync]: {
    chain: Chain.Zksync,
    ticker: 'ETH',
    logo: 'zksync',
    decimals: 18,
    priceProviderId: 'ethereum',
    contractAddress: '',
    isNativeToken: true,
  },
  [Chain.Dydx]: {
    chain: Chain.Dydx,
    ticker: 'DYDX',
    logo: 'dydx',
    decimals: 18,
    priceProviderId: 'dydx-chain',
    contractAddress: '',
    isNativeToken: true,
  },
  [Chain.Kujira]: {
    chain: Chain.Kujira,
    ticker: 'KUJI',
    logo: 'kuji',
    decimals: 6,
    priceProviderId: 'kujira',
    contractAddress: '',
    isNativeToken: true,
  },
  [Chain.Terra]: {
    chain: Chain.Terra,
    ticker: 'LUNA',
    logo: 'luna',
    decimals: 6,
    priceProviderId: 'terra-luna-2',
    contractAddress: '',
    isNativeToken: true,
  },
  [Chain.TerraClassic]: {
    chain: Chain.TerraClassic,
    ticker: 'LUNC',
    logo: 'lunc',
    decimals: 6,
    priceProviderId: 'terra-luna',
    contractAddress: '',
    isNativeToken: true,
  },
  [Chain.Sui]: {
    chain: Chain.Sui,
    ticker: 'SUI',
    logo: 'sui',
    decimals: 9,
    priceProviderId: 'sui',
    contractAddress: '',
    isNativeToken: true,
  },
  [Chain.Polkadot]: {
    chain: Chain.Polkadot,
    ticker: 'DOT',
    logo: 'dot',
    decimals: 10,
    priceProviderId: 'polkadot',
    contractAddress: '',
    isNativeToken: true,
  },
  [Chain.Noble]: {
    chain: Chain.Noble,
    ticker: 'USDC',
    logo: 'usdc',
    decimals: 6,
    priceProviderId: 'usd-coin',
    contractAddress: '',
    isNativeToken: true,
  },
  [Chain.Akash]: {
    chain: Chain.Akash,
    ticker: 'AKT',
    logo: 'akash',
    decimals: 6,
    priceProviderId: 'akash-network',
    contractAddress: '',
    isNativeToken: true,
  },
  [Chain.Cosmos]: {
    chain: Chain.Cosmos,
    ticker: 'ATOM',
    logo: 'atom',
    decimals: 6,
    priceProviderId: 'cosmos',
    contractAddress: '',
    isNativeToken: true,
  },
  [Chain.Osmosis]: {
    chain: Chain.Osmosis,
    ticker: 'OSMO',
    logo: 'osmo',
    decimals: 6,
    priceProviderId: 'osmosis',
    contractAddress: '',
    isNativeToken: true,
  },
};
