// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetOSArgs() {
  return window['go']['main']['App']['GetOSArgs']();
}

export function ReadTextFile(arg1) {
  return window['go']['main']['App']['ReadTextFile'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveFileBkp(arg1, arg2) {
  return window['go']['main']['App']['SaveFileBkp'](arg1, arg2);
}
