// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetOSArgs():Promise<Array<string>>;

export function ReadFileBase64(arg1:string):Promise<string>;

export function ReadTextFile(arg1:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<string>;

export function ShowNotification(arg1:string,arg2:string):Promise<void>;
