// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file vultisig/keysign/v1/1inch_swap_payload.proto (package vultisig.keysign.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Coin } from "./coin_pb";
import { file_vultisig_keysign_v1_coin } from "./coin_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file vultisig/keysign/v1/1inch_swap_payload.proto.
 */
export const file_vultisig_keysign_v1_1inch_swap_payload: GenFile = /*@__PURE__*/
  fileDesc("Cix2dWx0aXNpZy9rZXlzaWduL3YxLzFpbmNoX3N3YXBfcGF5bG9hZC5wcm90bxITdnVsdGlzaWcua2V5c2lnbi52MSJrChJPbmVJbmNoVHJhbnNhY3Rpb24SDAoEZnJvbRgBIAEoCRIKCgJ0bxgCIAEoCRIMCgRkYXRhGAMgASgJEg0KBXZhbHVlGAQgASgJEhEKCWdhc19wcmljZRgFIAEoCRILCgNnYXMYBiABKAMiVwoMT25lSW5jaFF1b3RlEhIKCmRzdF9hbW91bnQYASABKAkSMwoCdHgYAiABKAsyJy52dWx0aXNpZy5rZXlzaWduLnYxLk9uZUluY2hUcmFuc2FjdGlvbiLQAQoST25lSW5jaFN3YXBQYXlsb2FkEiwKCWZyb21fY29pbhgBIAEoCzIZLnZ1bHRpc2lnLmtleXNpZ24udjEuQ29pbhIqCgd0b19jb2luGAIgASgLMhkudnVsdGlzaWcua2V5c2lnbi52MS5Db2luEhMKC2Zyb21fYW1vdW50GAMgASgJEhkKEXRvX2Ftb3VudF9kZWNpbWFsGAQgASgJEjAKBXF1b3RlGAUgASgLMiEudnVsdGlzaWcua2V5c2lnbi52MS5PbmVJbmNoUXVvdGVCLwoTdnVsdGlzaWcua2V5c2lnbi52MVoTdnVsdGlzaWcva2V5c2lnbi92MboCAlZTYgZwcm90bzM", [file_vultisig_keysign_v1_coin]);

/**
 * @generated from message vultisig.keysign.v1.OneInchTransaction
 */
export type OneInchTransaction = Message<"vultisig.keysign.v1.OneInchTransaction"> & {
  /**
   * @generated from field: string from = 1;
   */
  from: string;

  /**
   * @generated from field: string to = 2;
   */
  to: string;

  /**
   * @generated from field: string data = 3;
   */
  data: string;

  /**
   * @generated from field: string value = 4;
   */
  value: string;

  /**
   * @generated from field: string gas_price = 5;
   */
  gasPrice: string;

  /**
   * @generated from field: int64 gas = 6;
   */
  gas: bigint;
};

/**
 * Describes the message vultisig.keysign.v1.OneInchTransaction.
 * Use `create(OneInchTransactionSchema)` to create a new message.
 */
export const OneInchTransactionSchema: GenMessage<OneInchTransaction> = /*@__PURE__*/
  messageDesc(file_vultisig_keysign_v1_1inch_swap_payload, 0);

/**
 * @generated from message vultisig.keysign.v1.OneInchQuote
 */
export type OneInchQuote = Message<"vultisig.keysign.v1.OneInchQuote"> & {
  /**
   * @generated from field: string dst_amount = 1;
   */
  dstAmount: string;

  /**
   * @generated from field: vultisig.keysign.v1.OneInchTransaction tx = 2;
   */
  tx?: OneInchTransaction;
};

/**
 * Describes the message vultisig.keysign.v1.OneInchQuote.
 * Use `create(OneInchQuoteSchema)` to create a new message.
 */
export const OneInchQuoteSchema: GenMessage<OneInchQuote> = /*@__PURE__*/
  messageDesc(file_vultisig_keysign_v1_1inch_swap_payload, 1);

/**
 * @generated from message vultisig.keysign.v1.OneInchSwapPayload
 */
export type OneInchSwapPayload = Message<"vultisig.keysign.v1.OneInchSwapPayload"> & {
  /**
   * @generated from field: vultisig.keysign.v1.Coin from_coin = 1;
   */
  fromCoin?: Coin;

  /**
   * @generated from field: vultisig.keysign.v1.Coin to_coin = 2;
   */
  toCoin?: Coin;

  /**
   * @generated from field: string from_amount = 3;
   */
  fromAmount: string;

  /**
   * @generated from field: string to_amount_decimal = 4;
   */
  toAmountDecimal: string;

  /**
   * @generated from field: vultisig.keysign.v1.OneInchQuote quote = 5;
   */
  quote?: OneInchQuote;
};

/**
 * Describes the message vultisig.keysign.v1.OneInchSwapPayload.
 * Use `create(OneInchSwapPayloadSchema)` to create a new message.
 */
export const OneInchSwapPayloadSchema: GenMessage<OneInchSwapPayload> = /*@__PURE__*/
  messageDesc(file_vultisig_keysign_v1_1inch_swap_payload, 2);

