// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file vultisig/keysign/v1/coin.proto (package vultisig.keysign.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file vultisig/keysign/v1/coin.proto.
 */
export const file_vultisig_keysign_v1_coin: GenFile = /*@__PURE__*/
  fileDesc("Ch52dWx0aXNpZy9rZXlzaWduL3YxL2NvaW4ucHJvdG8SE3Z1bHRpc2lnLmtleXNpZ24udjEivAEKBENvaW4SDQoFY2hhaW4YASABKAkSDgoGdGlja2VyGAIgASgJEg8KB2FkZHJlc3MYAyABKAkSGAoQY29udHJhY3RfYWRkcmVzcxgEIAEoCRIQCghkZWNpbWFscxgFIAEoBRIZChFwcmljZV9wcm92aWRlcl9pZBgGIAEoCRIXCg9pc19uYXRpdmVfdG9rZW4YByABKAgSFgoOaGV4X3B1YmxpY19rZXkYCCABKAkSDAoEbG9nbxgJIAEoCUJUChN2dWx0aXNpZy5rZXlzaWduLnYxWjhnaXRodWIuY29tL3Z1bHRpc2lnL2NvbW1vbmRhdGEvZ28vdnVsdGlzaWcva2V5c2lnbi92MTt2MboCAlZTYgZwcm90bzM");

/**
 * Coin only contains information that the app can use it to identify the relevant coin in the vault
 *
 * @generated from message vultisig.keysign.v1.Coin
 */
export type Coin = Message<"vultisig.keysign.v1.Coin"> & {
  /**
   * @generated from field: string chain = 1;
   */
  chain: string;

  /**
   * @generated from field: string ticker = 2;
   */
  ticker: string;

  /**
   * @generated from field: string address = 3;
   */
  address: string;

  /**
   * @generated from field: string contract_address = 4;
   */
  contractAddress: string;

  /**
   * @generated from field: int32 decimals = 5;
   */
  decimals: number;

  /**
   * @generated from field: string price_provider_id = 6;
   */
  priceProviderId: string;

  /**
   * @generated from field: bool is_native_token = 7;
   */
  isNativeToken: boolean;

  /**
   * @generated from field: string hex_public_key = 8;
   */
  hexPublicKey: string;

  /**
   * @generated from field: string logo = 9;
   */
  logo: string;
};

/**
 * Describes the message vultisig.keysign.v1.Coin.
 * Use `create(CoinSchema)` to create a new message.
 */
export const CoinSchema: GenMessage<Coin> = /*@__PURE__*/
  messageDesc(file_vultisig_keysign_v1_coin, 0);

