// @generated by protoc-gen-es v2.2.4 with parameter "target=ts"
// @generated from file vultisig/keysign/v1/custom_message_payload.proto (package vultisig.keysign.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file vultisig/keysign/v1/custom_message_payload.proto.
 */
export const file_vultisig_keysign_v1_custom_message_payload: GenFile = /*@__PURE__*/
  fileDesc("CjB2dWx0aXNpZy9rZXlzaWduL3YxL2N1c3RvbV9tZXNzYWdlX3BheWxvYWQucHJvdG8SE3Z1bHRpc2lnLmtleXNpZ24udjEidQoUQ3VzdG9tTWVzc2FnZVBheWxvYWQSDgoGbWV0aG9kGAEgASgJEg8KB21lc3NhZ2UYAiABKAkSHgoWdmF1bHRfcHVibGljX2tleV9lY2RzYRgDIAEoCRIcChR2YXVsdF9sb2NhbF9wYXJ0eV9pZBgEIAEoCUJUChN2dWx0aXNpZy5rZXlzaWduLnYxWjhnaXRodWIuY29tL3Z1bHRpc2lnL2NvbW1vbmRhdGEvZ28vdnVsdGlzaWcva2V5c2lnbi92MTt2MboCAlZTYgZwcm90bzM");

/**
 * @generated from message vultisig.keysign.v1.CustomMessagePayload
 */
export type CustomMessagePayload = Message<"vultisig.keysign.v1.CustomMessagePayload"> & {
  /**
   * @generated from field: string method = 1;
   */
  method: string;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * @generated from field: string vault_public_key_ecdsa = 3;
   */
  vaultPublicKeyEcdsa: string;

  /**
   * @generated from field: string vault_local_party_id = 4;
   */
  vaultLocalPartyId: string;
};

/**
 * Describes the message vultisig.keysign.v1.CustomMessagePayload.
 * Use `create(CustomMessagePayloadSchema)` to create a new message.
 */
export const CustomMessagePayloadSchema: GenMessage<CustomMessagePayload> = /*@__PURE__*/
  messageDesc(file_vultisig_keysign_v1_custom_message_payload, 0);

