// @generated by protoc-gen-es v2.2.4 with parameter "target=ts"
// @generated from file vultisig/keysign/v1/erc20_approve_payload.proto (package vultisig.keysign.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file vultisig/keysign/v1/erc20_approve_payload.proto.
 */
export const file_vultisig_keysign_v1_erc20_approve_payload: GenFile = /*@__PURE__*/
  fileDesc("Ci92dWx0aXNpZy9rZXlzaWduL3YxL2VyYzIwX2FwcHJvdmVfcGF5bG9hZC5wcm90bxITdnVsdGlzaWcua2V5c2lnbi52MSI2ChNFcmMyMEFwcHJvdmVQYXlsb2FkEg4KBmFtb3VudBgBIAEoCRIPCgdzcGVuZGVyGAIgASgJQlQKE3Z1bHRpc2lnLmtleXNpZ24udjFaOGdpdGh1Yi5jb20vdnVsdGlzaWcvY29tbW9uZGF0YS9nby92dWx0aXNpZy9rZXlzaWduL3YxO3YxugICVlNiBnByb3RvMw");

/**
 * @generated from message vultisig.keysign.v1.Erc20ApprovePayload
 */
export type Erc20ApprovePayload = Message<"vultisig.keysign.v1.Erc20ApprovePayload"> & {
  /**
   * @generated from field: string amount = 1;
   */
  amount: string;

  /**
   * @generated from field: string spender = 2;
   */
  spender: string;
};

/**
 * Describes the message vultisig.keysign.v1.Erc20ApprovePayload.
 * Use `create(Erc20ApprovePayloadSchema)` to create a new message.
 */
export const Erc20ApprovePayloadSchema: GenMessage<Erc20ApprovePayload> = /*@__PURE__*/
  messageDesc(file_vultisig_keysign_v1_erc20_approve_payload, 0);

