// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file vultisig/keysign/v1/tron_contract_payload.proto (package vultisig.keysign.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file vultisig/keysign/v1/tron_contract_payload.proto.
 */
export const file_vultisig_keysign_v1_tron_contract_payload: GenFile = /*@__PURE__*/
  fileDesc("Ci92dWx0aXNpZy9rZXlzaWduL3YxL3Ryb25fY29udHJhY3RfcGF5bG9hZC5wcm90bxITdnVsdGlzaWcua2V5c2lnbi52MSJYChtUcm9uVHJhbnNmZXJDb250cmFjdFBheWxvYWQSEgoKdG9fYWRkcmVzcxgBIAEoCRIVCg1vd25lcl9hZGRyZXNzGAIgASgJEg4KBmFtb3VudBgDIAEoCUJUChN2dWx0aXNpZy5rZXlzaWduLnYxWjhnaXRodWIuY29tL3Z1bHRpc2lnL2NvbW1vbmRhdGEvZ28vdnVsdGlzaWcva2V5c2lnbi92MTt2MboCAlZTYgZwcm90bzM");

/**
 * @generated from message vultisig.keysign.v1.TronTransferContractPayload
 */
export type TronTransferContractPayload = Message<"vultisig.keysign.v1.TronTransferContractPayload"> & {
  /**
   * @generated from field: string to_address = 1;
   */
  toAddress: string;

  /**
   * @generated from field: string owner_address = 2;
   */
  ownerAddress: string;

  /**
   * @generated from field: string amount = 3;
   */
  amount: string;
};

/**
 * Describes the message vultisig.keysign.v1.TronTransferContractPayload.
 * Use `create(TronTransferContractPayloadSchema)` to create a new message.
 */
export const TronTransferContractPayloadSchema: GenMessage<TronTransferContractPayload> = /*@__PURE__*/
  messageDesc(file_vultisig_keysign_v1_tron_contract_payload, 0);

