// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file vultisig/keysign/v1/tron_contract_payload.proto (package vultisig.keysign.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file vultisig/keysign/v1/tron_contract_payload.proto.
 */
export const file_vultisig_keysign_v1_tron_contract_payload: GenFile = /*@__PURE__*/
  fileDesc("Ci92dWx0aXNpZy9rZXlzaWduL3YxL3Ryb25fY29udHJhY3RfcGF5bG9hZC5wcm90bxITdnVsdGlzaWcua2V5c2lnbi52MSJYChtUcm9uVHJhbnNmZXJDb250cmFjdFBheWxvYWQSEgoKdG9fYWRkcmVzcxgBIAEoCRIVCg1vd25lcl9hZGRyZXNzGAIgASgJEg4KBmFtb3VudBgDIAEoCSLuAQofVHJvblRyaWdnZXJTbWFydENvbnRyYWN0UGF5bG9hZBIVCg1vd25lcl9hZGRyZXNzGAEgASgJEhgKEGNvbnRyYWN0X2FkZHJlc3MYAiABKAkSFwoKY2FsbF92YWx1ZRgDIAEoCUgAiAEBEh0KEGNhbGxfdG9rZW5fdmFsdWUYBCABKAlIAYgBARIVCgh0b2tlbl9pZBgFIAEoBUgCiAEBEhEKBGRhdGEYBiABKAlIA4gBAUINCgtfY2FsbF92YWx1ZUITChFfY2FsbF90b2tlbl92YWx1ZUILCglfdG9rZW5faWRCBwoFX2RhdGEicQogVHJvblRyYW5zZmVyQXNzZXRDb250cmFjdFBheWxvYWQSEgoKdG9fYWRkcmVzcxgBIAEoCRIVCg1vd25lcl9hZGRyZXNzGAIgASgJEg4KBmFtb3VudBgDIAEoCRISCgphc3NldF9uYW1lGAQgASgJQlQKE3Z1bHRpc2lnLmtleXNpZ24udjFaOGdpdGh1Yi5jb20vdnVsdGlzaWcvY29tbW9uZGF0YS9nby92dWx0aXNpZy9rZXlzaWduL3YxO3YxugICVlNiBnByb3RvMw");

/**
 * @generated from message vultisig.keysign.v1.TronTransferContractPayload
 */
export type TronTransferContractPayload = Message<"vultisig.keysign.v1.TronTransferContractPayload"> & {
  /**
   * @generated from field: string to_address = 1;
   */
  toAddress: string;

  /**
   * @generated from field: string owner_address = 2;
   */
  ownerAddress: string;

  /**
   * @generated from field: string amount = 3;
   */
  amount: string;
};

/**
 * Describes the message vultisig.keysign.v1.TronTransferContractPayload.
 * Use `create(TronTransferContractPayloadSchema)` to create a new message.
 */
export const TronTransferContractPayloadSchema: GenMessage<TronTransferContractPayload> = /*@__PURE__*/
  messageDesc(file_vultisig_keysign_v1_tron_contract_payload, 0);

/**
 * @generated from message vultisig.keysign.v1.TronTriggerSmartContractPayload
 */
export type TronTriggerSmartContractPayload = Message<"vultisig.keysign.v1.TronTriggerSmartContractPayload"> & {
  /**
   * @generated from field: string owner_address = 1;
   */
  ownerAddress: string;

  /**
   * @generated from field: string contract_address = 2;
   */
  contractAddress: string;

  /**
   * @generated from field: optional string call_value = 3;
   */
  callValue?: string;

  /**
   * @generated from field: optional string call_token_value = 4;
   */
  callTokenValue?: string;

  /**
   * @generated from field: optional int32 token_id = 5;
   */
  tokenId?: number;

  /**
   * @generated from field: optional string data = 6;
   */
  data?: string;
};

/**
 * Describes the message vultisig.keysign.v1.TronTriggerSmartContractPayload.
 * Use `create(TronTriggerSmartContractPayloadSchema)` to create a new message.
 */
export const TronTriggerSmartContractPayloadSchema: GenMessage<TronTriggerSmartContractPayload> = /*@__PURE__*/
  messageDesc(file_vultisig_keysign_v1_tron_contract_payload, 1);

/**
 * @generated from message vultisig.keysign.v1.TronTransferAssetContractPayload
 */
export type TronTransferAssetContractPayload = Message<"vultisig.keysign.v1.TronTransferAssetContractPayload"> & {
  /**
   * @generated from field: string to_address = 1;
   */
  toAddress: string;

  /**
   * @generated from field: string owner_address = 2;
   */
  ownerAddress: string;

  /**
   * @generated from field: string amount = 3;
   */
  amount: string;

  /**
   * @generated from field: string asset_name = 4;
   */
  assetName: string;
};

/**
 * Describes the message vultisig.keysign.v1.TronTransferAssetContractPayload.
 * Use `create(TronTransferAssetContractPayloadSchema)` to create a new message.
 */
export const TronTransferAssetContractPayloadSchema: GenMessage<TronTransferAssetContractPayload> = /*@__PURE__*/
  messageDesc(file_vultisig_keysign_v1_tron_contract_payload, 2);

