// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file vultisig/keysign/v1/wasm_execute_contract_payload.proto (package vultisig.keysign.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file vultisig/keysign/v1/wasm_execute_contract_payload.proto.
 */
export const file_vultisig_keysign_v1_wasm_execute_contract_payload: GenFile = /*@__PURE__*/
  fileDesc("Cjd2dWx0aXNpZy9rZXlzaWduL3YxL3dhc21fZXhlY3V0ZV9jb250cmFjdF9wYXlsb2FkLnByb3RvEhN2dWx0aXNpZy5rZXlzaWduLnYxIisKCkNvc21vc0NvaW4SDQoFZGVub20YASABKAkSDgoGYW1vdW50GAIgASgJIq8BCglDb3Ntb3NGZWUSLwoGYW1vdW50GAEgAygLMh8udnVsdGlzaWcua2V5c2lnbi52MS5Db3Ntb3NDb2luEgsKA2dhcxgCIAEoCRISCgVwYXllchgDIAEoCUgAiAEBEhQKB2dyYW50ZXIYBCABKAlIAYgBARIWCglmZWVfcGF5ZXIYBSABKAlIAogBAUIICgZfcGF5ZXJCCgoIX2dyYW50ZXJCDAoKX2ZlZV9wYXllciIoCglDb3Ntb3NNc2cSDAoEdHlwZRgBIAEoCRINCgV2YWx1ZRgCIAEoCSJmCglTaWduQW1pbm8SKwoDZmVlGAEgASgLMh4udnVsdGlzaWcua2V5c2lnbi52MS5Db3Ntb3NGZWUSLAoEbXNncxgCIAMoCzIeLnZ1bHRpc2lnLmtleXNpZ24udjEuQ29zbW9zTXNnImMKClNpZ25EaXJlY3QSEgoKYm9keV9ieXRlcxgBIAEoCRIXCg9hdXRoX2luZm9fYnl0ZXMYAiABKAkSEAoIY2hhaW5faWQYAyABKAkSFgoOYWNjb3VudF9udW1iZXIYBCABKAkikwEKGldhc21FeGVjdXRlQ29udHJhY3RQYXlsb2FkEhYKDnNlbmRlcl9hZGRyZXNzGAEgASgJEhgKEGNvbnRyYWN0X2FkZHJlc3MYAiABKAkSEwoLZXhlY3V0ZV9tc2cYAyABKAkSLgoFY29pbnMYBCADKAsyHy52dWx0aXNpZy5rZXlzaWduLnYxLkNvc21vc0NvaW5CVAoTdnVsdGlzaWcua2V5c2lnbi52MVo4Z2l0aHViLmNvbS92dWx0aXNpZy9jb21tb25kYXRhL2dvL3Z1bHRpc2lnL2tleXNpZ24vdjE7djG6AgJWU2IGcHJvdG8z");

/**
 * @generated from message vultisig.keysign.v1.CosmosCoin
 */
export type CosmosCoin = Message<"vultisig.keysign.v1.CosmosCoin"> & {
  /**
   * @generated from field: string denom = 1;
   */
  denom: string;

  /**
   * @generated from field: string amount = 2;
   */
  amount: string;
};

/**
 * Describes the message vultisig.keysign.v1.CosmosCoin.
 * Use `create(CosmosCoinSchema)` to create a new message.
 */
export const CosmosCoinSchema: GenMessage<CosmosCoin> = /*@__PURE__*/
  messageDesc(file_vultisig_keysign_v1_wasm_execute_contract_payload, 0);

/**
 * @generated from message vultisig.keysign.v1.CosmosFee
 */
export type CosmosFee = Message<"vultisig.keysign.v1.CosmosFee"> & {
  /**
   * @generated from field: repeated vultisig.keysign.v1.CosmosCoin amount = 1;
   */
  amount: CosmosCoin[];

  /**
   * @generated from field: string gas = 2;
   */
  gas: string;

  /**
   * @generated from field: optional string payer = 3;
   */
  payer?: string;

  /**
   * @generated from field: optional string granter = 4;
   */
  granter?: string;

  /**
   * @generated from field: optional string fee_payer = 5;
   */
  feePayer?: string;
};

/**
 * Describes the message vultisig.keysign.v1.CosmosFee.
 * Use `create(CosmosFeeSchema)` to create a new message.
 */
export const CosmosFeeSchema: GenMessage<CosmosFee> = /*@__PURE__*/
  messageDesc(file_vultisig_keysign_v1_wasm_execute_contract_payload, 1);

/**
 * @generated from message vultisig.keysign.v1.CosmosMsg
 */
export type CosmosMsg = Message<"vultisig.keysign.v1.CosmosMsg"> & {
  /**
   * @generated from field: string type = 1;
   */
  type: string;

  /**
   * @generated from field: string value = 2;
   */
  value: string;
};

/**
 * Describes the message vultisig.keysign.v1.CosmosMsg.
 * Use `create(CosmosMsgSchema)` to create a new message.
 */
export const CosmosMsgSchema: GenMessage<CosmosMsg> = /*@__PURE__*/
  messageDesc(file_vultisig_keysign_v1_wasm_execute_contract_payload, 2);

/**
 * @generated from message vultisig.keysign.v1.SignAmino
 */
export type SignAmino = Message<"vultisig.keysign.v1.SignAmino"> & {
  /**
   * @generated from field: vultisig.keysign.v1.CosmosFee fee = 1;
   */
  fee?: CosmosFee;

  /**
   * @generated from field: repeated vultisig.keysign.v1.CosmosMsg msgs = 2;
   */
  msgs: CosmosMsg[];
};

/**
 * Describes the message vultisig.keysign.v1.SignAmino.
 * Use `create(SignAminoSchema)` to create a new message.
 */
export const SignAminoSchema: GenMessage<SignAmino> = /*@__PURE__*/
  messageDesc(file_vultisig_keysign_v1_wasm_execute_contract_payload, 3);

/**
 * @generated from message vultisig.keysign.v1.SignDirect
 */
export type SignDirect = Message<"vultisig.keysign.v1.SignDirect"> & {
  /**
   * @generated from field: string body_bytes = 1;
   */
  bodyBytes: string;

  /**
   * @generated from field: string auth_info_bytes = 2;
   */
  authInfoBytes: string;

  /**
   * @generated from field: string chain_id = 3;
   */
  chainId: string;

  /**
   * @generated from field: string account_number = 4;
   */
  accountNumber: string;
};

/**
 * Describes the message vultisig.keysign.v1.SignDirect.
 * Use `create(SignDirectSchema)` to create a new message.
 */
export const SignDirectSchema: GenMessage<SignDirect> = /*@__PURE__*/
  messageDesc(file_vultisig_keysign_v1_wasm_execute_contract_payload, 4);

/**
 * @generated from message vultisig.keysign.v1.WasmExecuteContractPayload
 */
export type WasmExecuteContractPayload = Message<"vultisig.keysign.v1.WasmExecuteContractPayload"> & {
  /**
   * @generated from field: string sender_address = 1;
   */
  senderAddress: string;

  /**
   * @generated from field: string contract_address = 2;
   */
  contractAddress: string;

  /**
   * @generated from field: string execute_msg = 3;
   */
  executeMsg: string;

  /**
   * @generated from field: repeated vultisig.keysign.v1.CosmosCoin coins = 4;
   */
  coins: CosmosCoin[];
};

/**
 * Describes the message vultisig.keysign.v1.WasmExecuteContractPayload.
 * Use `create(WasmExecuteContractPayloadSchema)` to create a new message.
 */
export const WasmExecuteContractPayloadSchema: GenMessage<WasmExecuteContractPayload> = /*@__PURE__*/
  messageDesc(file_vultisig_keysign_v1_wasm_execute_contract_payload, 5);

