import type {
  ChainObjRef,
  ChainStrRef,
  CurrencyRef,
  LanguageRef,
} from '@clients/extension/src/utils/interfaces'
import { Chain } from '@core/chain/Chain'
import keyMirror from 'keymirror'
export enum CosmosMsgType {
  MSG_SEND = 'cosmos-sdk/MsgSend',
}

export enum ChainTicker {
  BTC = 'BTC',
  DOGE = 'DOGE',
  LTC = 'LTC',
  BCH = 'BCH',
  ETH = 'ETH',
  AVAX = 'AVAX',
  BNB = 'BNB',
  GAIA = 'GAIA',
  THOR = 'RUNE',
  BSC = 'BSC',
  BASE = 'BASE',
  SOL = 'SOL',
  CRO = 'CRO',
  DYDX = 'DYDX',
  DASH = 'DASH',
  ATOM = 'ATOM',
  KUJI = 'KUJI',
  CACAO = 'CACAO',
  OSMO = 'OSMO',
  MATIC = 'MATIC',
}

export enum MessageKey {
  BITCOIN_REQUEST = 'bitcoin',
  BITCOIN_CASH_REQUEST = 'bitcoincash',
  COSMOS_REQUEST = 'cosmos',
  DASH_REQUEST = 'dash',
  DOGECOIN_REQUEST = 'dogecoin',
  ETHEREUM_REQUEST = 'ethereum',
  LITECOIN_REQUEST = 'litecoin',
  MAYA_REQUEST = 'maya',
  SOLANA_REQUEST = 'solana',
  THOR_REQUEST = 'thor',
  PRIORITY = 'priority',
  VAULT = 'vault',
  VAULTS = 'vaults',
}

export enum SenderKey {
  PAGE = 'page',
  RELAY = 'relay',
}

export enum Currency {
  AUD = 'AUD',
  CAD = 'CAD',
  CNY = 'CNY',
  EUR = 'EUR',
  GBP = 'GBP',
  JPY = 'JPY',
  RUB = 'RUB',
  SEK = 'SEK',
  SGD = 'SGD',
  USD = 'USD',
}

export enum Instance {
  ACCOUNTS = 'accounts',
  TRANSACTION = 'transaction',
  VAULT = 'vault',
  VAULTS = 'vaults',
}

export enum Language {
  CROATIA = 'hr',
  DUTCH = 'nl',
  ENGLISH = 'en',
  GERMAN = 'de',
  ITALIAN = 'it',
  RUSSIAN = 'ru',
  PORTUGUESE = 'pt',
  SPANISH = 'es',
}

export enum EventMethod {
  ACCOUNTS_CHANGED = 'accountsChanged',
  CHAIN_CHANGED = 'chainChanged',
  CONNECT = 'connect',
  DISCONNECT = 'diconnect',
  ERROR = 'ERROR',
  MESSAGE = 'MESSAGE',
  NETWORK_CHANGED = 'networkChanged',
}

export enum TssKeysignType {
  ECDSA = 'ECDSA',
  EdDSA = 'EdDSA',
}

export namespace RequestMethod {
  export enum CTRL {
    DEPOSIT = 'deposit',
    GET_UNSPENT_UTXOS = 'get_unspent_utxos',
    REQUEST_ACCOUNTS_AND_KEYS = 'request_accounts_and_keys',
    SIGN_MESSAGE = 'sign_message',
    SIGN_PSBT = 'sign_psbt',
    SIGN_TRANSACTION = 'sign_transaction',
    TRANSFER = 'transfer',
  }

  export enum METAMASK {
    ETH_ACCOUNTS = 'eth_accounts',
    ETH_BLOB_BASE_FEE = 'eth_blobBaseFee',
    ETH_BLOCK_NUMBER = 'eth_blockNumber',
    ETH_CALL = 'eth_call',
    ETH_CHAIN_ID = 'eth_chainId',
    ETH_COINBASE = 'eth_coinbase',
    ETH_DECRYPT = 'eth_decrypt',
    ETH_ESTIMATE_GAS = 'eth_estimateGas',
    ETH_FEE_HISTORY = 'eth_feeHistory',
    ETH_GAS_PRICE = 'eth_gasPrice',
    ETH_GET_BALANCE = 'eth_getBalance',
    ETH_GET_BLOCK_BY_HASH = 'eth_getBlockByHash',
    ETH_GET_BLOCK_BY_NUMBER = 'eth_getBlockByNumber',
    ETH_GET_BLOCK_RECEIPTS = 'eth_getBlockReceipts',
    ETH_GET_BLOCK_TRANSACTION_COUNT_BY_HASH = 'eth_getBlockTransactionCountByHash',
    ETH_GET_BLOCK_TRANSACTION_COUNT_BY_NUMBER = 'eth_getBlockTransactionCountByNumber',
    ETH_GET_CODE = 'eth_getCode',
    ETH_GET_ENCRYPTION_PUBLIC_KEY = 'eth_getEncryptionPublicKey',
    ETH_GET_FILTER_CHANGES = 'eth_getFilterChanges',
    ETH_GET_FILTER_LOGS = 'eth_getFilterLogs',
    ETH_GET_LOGS = 'eth_getLogs',
    ETH_GET_PROOF = 'eth_getProof',
    ETH_GET_STORAGEAT = 'eth_getStorageAt',
    ETH_GET_TRANSACTION_BY_BLOCK_HASH_AND_INDEX = 'eth_getTransactionByBlockHashAndIndex',
    ETH_GET_TRANSACTION_BY_BLOCK_NUMBER_AND_INDEX = 'eth_getTransactionByBlockNumberAndIndex',
    ETH_GET_TRANSACTION_BY_HASH = 'eth_getTransactionByHash',
    ETH_GET_TRANSACTION_COUNT = 'eth_getTransactionCount',
    ETH_GET_TRANSACTION_RECEIPT = 'eth_getTransactionReceipt',
    ETH_GET_UNCLE_COUNT_BY_BLOCK_HASH = 'eth_getUncleCountByBlockHash',
    ETH_GET_UNCLE_COUNT_BY_BLOCK_NUMBER = 'eth_getUncleCountByBlockNumber',
    ETH_MAX_PRIORITY_FEE_PER_GAS = 'eth_maxPriorityFeePerGas',
    ETH_NEW_BLOCK_FILTER = 'eth_newBlockFilter',
    ETH_NEW_FILTER = 'eth_newFilter',
    ETH_NEW_PENDING_TRANSACTION_FILTER = 'eth_newPendingTransactionFilter',
    ETH_REQUEST_ACCOUNTS = 'eth_requestAccounts',
    ETH_SEND_RAW_TRANSACTION = 'eth_sendRawTransaction',
    ETH_SEND_TRANSACTION = 'eth_sendTransaction',
    ETH_SIGN = 'eth_sign',
    ETH_SIGN_TYPED_DATA_V4 = 'eth_signTypedData_v4',
    ETH_SUBSCRIBE = 'eth_subscribe',
    ETH_SYNCING = 'eth_syncing',
    ETH_UNINSTALL_FILTER = 'eth_uninstallFilter',
    ETH_UNSUBSCRIBE = 'eth_unsubscribe',
    NET_VERSION = 'net_version',
    PERSONAL_SIGN = 'personal_sign',
    WALLET_ADD_ETHEREUM_CHAIN = 'wallet_addEthereumChain',
    WALLET_GET_PERMISSIONS = 'wallet_getPermissions',
    WALLET_REGISTER_ONBOARDING = 'wallet_registerOnboarding',
    WALLET_REQUEST_PERMISSIONS = 'wallet_requestPermissions',
    WALLET_REVOKE_PERMISSIONS = 'wallet_revokePermissions',
    WALLET_SWITCH_ETHEREUM_CHAIN = 'wallet_switchEthereumChain',
    WALLET_SCAN_QR_CODE = 'wallet_scanQRCode',
    WALLET_WATCH_ASSET = 'wallet_watchAsset',
    WEB3_CLIENT_VERSION = 'web3_clientVersion',
  }

  export enum VULTISIG {
    GET_ACCOUNTS = 'get_accounts',
    CHAIN_ID = 'chain_id',
    DEPOSIT_TRANSACTION = 'deposit_transaction',
    GET_TRANSACTION_BY_HASH = 'get_transaction_by_hash',
    REQUEST_ACCOUNTS = 'request_accounts',
    SEND_TRANSACTION = 'send_transaction',
    WALLET_ADD_CHAIN = 'wallet_add_chain',
    WALLET_SWITCH_CHAIN = 'wallet_switch_chain',
  }
}

export const storageKey = keyMirror({
  CURRENCY: true,
  LANGUAGE: true,
  VAULTS: true,
})

export const errorKey = keyMirror({
  FAIL_TO_GET_ACCOUNTS: true,
  FAIL_TO_GET_ADDRESS: true,
  FAIL_TO_GET_VAULT: true,
  FAIL_TO_GET_VAULTS: true,
  FAIL_TO_GET_TRANSACTION: true,
  FAIL_TO_INIT_WASM: true,
  INVALID_CHAIN: true,
  INVALID_EXTENSION: true,
  INVALID_FILE: true,
  INVALID_QRCODE: true,
  INVALID_VAULT: true,
})

export const currencyName: CurrencyRef = {
  [Currency.AUD]: 'Australian Dollar',
  [Currency.CAD]: 'Canadian Dollar',
  [Currency.CNY]: 'Chinese Yuan',
  [Currency.EUR]: 'European Euro',
  [Currency.GBP]: 'British Pound',
  [Currency.JPY]: 'Japanese Yen',
  [Currency.RUB]: 'Russian Ruble',
  [Currency.SEK]: 'Swedish Krona',
  [Currency.SGD]: 'Singapore Dollar',
  [Currency.USD]: 'United States Dollar',
}

export const currencySymbol: CurrencyRef = {
  [Currency.AUD]: 'A$',
  [Currency.CAD]: 'C$',
  [Currency.CNY]: '¥',
  [Currency.EUR]: '€',
  [Currency.GBP]: '£',
  [Currency.JPY]: '¥',
  [Currency.RUB]: '₽',
  [Currency.SEK]: 'kr',
  [Currency.SGD]: 'S$',
  [Currency.USD]: '$',
}

export const languageName: LanguageRef = {
  [Language.CROATIA]: 'Hrvatski',
  [Language.DUTCH]: 'Dutch',
  [Language.ENGLISH]: 'English',
  [Language.GERMAN]: 'Deutsch',
  [Language.ITALIAN]: 'Italiano',
  [Language.PORTUGUESE]: 'Português',
  [Language.RUSSIAN]: 'Русский',
  [Language.SPANISH]: 'Espanol',
}

export const explorerUrl: ChainStrRef = {
  [Chain.Arbitrum]: 'https://arbiscan.io',
  [Chain.Avalanche]: 'https://snowtrace.io',
  [Chain.Base]: 'https://basescan.org',
  [Chain.Bitcoin]: 'https://blockchair.com/bitcoin',
  [Chain.BitcoinCash]: 'https://blockchair.com/bitcoin-cash',
  [Chain.Blast]: 'https://blastscan.io',
  [Chain.BSC]: 'https://bscscan.com',
  [Chain.CronosChain]: 'https://cronoscan.com',
  [Chain.Dash]: 'https://blockchair.com/dash',
  [Chain.Dogecoin]: 'https://blockchair.com/dogecoin',
  [Chain.Dydx]: 'https://www.mintscan.io/dydx',
  [Chain.Ethereum]: 'https://etherscan.io',
  [Chain.Cosmos]: 'https://www.mintscan.io/cosmos',
  [Chain.Kujira]: 'https://finder.kujira.network',
  [Chain.Litecoin]: 'https://blockchair.com/litecoin',
  [Chain.MayaChain]: 'https://www.mayascan.org',
  [Chain.Optimism]: 'https://optimistic.etherscan.io',
  [Chain.Osmosis]: 'https://www.mintscan.io/osmosis',
  [Chain.Polkadot]: 'https://polkadot.subscan.io/account',
  [Chain.Polygon]: 'https://polygonscan.com',
  [Chain.Solana]: 'https://solscan.io',
  [Chain.Sui]: '',
  [Chain.Terra]: '',
  [Chain.TerraClassic]: '',
  [Chain.THORChain]: 'https://thorchain.net',
  [Chain.Ton]: 'https://tonscan.org/',
  [Chain.Ripple]: '',
  [Chain.Zksync]: 'https://explorer.zksync.io',
  [Chain.Noble]: '',
  [Chain.Akash]: '',
}

export const rpcUrl: ChainStrRef = {
  [Chain.Arbitrum]: 'https://api.vultisig.com/arb/',
  [Chain.Avalanche]: 'https://api.vultisig.com/avax/',
  [Chain.Base]: 'https://api.vultisig.com/base/',
  [Chain.Bitcoin]: '',
  [Chain.BitcoinCash]: '',
  [Chain.Blast]: 'https://api.vultisig.com/blast/',
  [Chain.BSC]: 'https://api.vultisig.com/bnb/',
  [Chain.CronosChain]: 'https://cronos-evm-rpc.publicnode.com',
  [Chain.Dash]: '',
  [Chain.Dogecoin]: '',
  [Chain.Dydx]: 'https://dydx-rpc.publicnode.com',
  [Chain.Ethereum]: 'https://api.vultisig.com/eth/',
  [Chain.Cosmos]: 'https://cosmos-rpc.publicnode.com',
  [Chain.Kujira]: 'https://kujira-rpc.publicnode.com',
  [Chain.Litecoin]: '',
  [Chain.MayaChain]: '',
  [Chain.Optimism]: 'https://api.vultisig.com/opt/',
  [Chain.Osmosis]: 'https://osmosis-rpc.publicnode.com',
  [Chain.Polkadot]: '',
  [Chain.Polygon]: 'https://api.vultisig.com/polygon/',
  [Chain.Solana]: 'https://solana-rpc.publicnode.com',
  [Chain.Sui]: '',
  [Chain.Terra]: '',
  [Chain.TerraClassic]: '',
  [Chain.THORChain]: 'https://rpc.ninerealms.com/',
  [Chain.Ton]: '',
  [Chain.Ripple]: 'https://rpc.ninerealms.com/',
  [Chain.Zksync]: 'https://api.vultisig.com/zksync/',
  [Chain.Noble]: '',
  [Chain.Akash]: '',
}

export const chains: ChainObjRef = {
  [Chain.Arbitrum]: {
    cmcId: 1027,
    decimals: 18,
    id: '0xa4b1',
    name: Chain.Arbitrum,
    ticker: ChainTicker.ETH,
  },
  [Chain.Avalanche]: {
    cmcId: 5805,
    decimals: 18,
    id: '0xa86a',
    name: Chain.Avalanche,
    ticker: ChainTicker.AVAX,
  },
  [Chain.Base]: {
    cmcId: 1027,
    decimals: 18,
    id: '0x2105',
    name: Chain.Base,
    ticker: ChainTicker.ETH,
  },
  [Chain.Bitcoin]: {
    cmcId: 1,
    decimals: 8,
    id: '0x1f96',
    name: Chain.Bitcoin,
    ticker: ChainTicker.BTC,
  },
  [Chain.BitcoinCash]: {
    cmcId: 1831,
    decimals: 8,
    id: '0x2710',
    name: Chain.BitcoinCash,
    ticker: ChainTicker.BCH,
  },
  [Chain.Blast]: {
    cmcId: 1027,
    decimals: 18,
    id: '0x13e31',
    name: Chain.Blast,
    ticker: ChainTicker.ETH,
  },
  [Chain.BSC]: {
    cmcId: 1839,
    decimals: 18,
    id: '0x38',
    name: Chain.BSC,
    ticker: ChainTicker.BSC,
  },
  [Chain.CronosChain]: {
    cmcId: 3635,
    decimals: 18,
    id: '0x19',
    name: Chain.CronosChain,
    ticker: ChainTicker.CRO,
  },
  [Chain.Dogecoin]: {
    cmcId: 74,
    decimals: 8,
    id: '0x7d0',
    name: Chain.Dogecoin,
    ticker: ChainTicker.DOGE,
  },
  [Chain.Dydx]: {
    cmcId: 28324,
    decimals: 18,
    id: 'dydx-1',
    name: Chain.Dydx,
    ticker: ChainTicker.DYDX,
  },
  [Chain.Ethereum]: {
    cmcId: 1027,
    decimals: 18,
    id: '0x1',
    name: Chain.Ethereum,
    ticker: ChainTicker.ETH,
  },
  [Chain.Dash]: {
    cmcId: 131,
    decimals: 8,
    id: 'Dash_dash',
    name: Chain.Dash,
    ticker: ChainTicker.DASH,
  },
  [Chain.Cosmos]: {
    cmcId: 3794,
    decimals: 6,
    id: 'cosmoshub-4',
    name: Chain.Cosmos,
    ticker: ChainTicker.ATOM,
  },
  [Chain.Kujira]: {
    cmcId: 15185,
    decimals: 6,
    id: 'kaiyo-1',
    name: Chain.Kujira,
    ticker: ChainTicker.KUJI,
  },
  [Chain.Litecoin]: {
    cmcId: 2,
    decimals: 8,
    id: 'Litecoin_litecoin',
    name: Chain.Litecoin,
    ticker: ChainTicker.LTC,
  },
  [Chain.MayaChain]: {
    cmcId: 23534,
    decimals: 10,
    id: 'MayaChain-1',
    name: Chain.MayaChain,
    ticker: ChainTicker.CACAO,
  },
  [Chain.Optimism]: {
    cmcId: 1027,
    decimals: 18,
    id: 'Optimism_optimism',
    name: Chain.Optimism,
    ticker: ChainTicker.ETH,
  },
  [Chain.Osmosis]: {
    cmcId: 12220,
    decimals: 6,
    id: 'osmosis-1',
    name: Chain.Osmosis,
    ticker: ChainTicker.OSMO,
  },
  [Chain.Polygon]: {
    cmcId: 3890,
    decimals: 18,
    id: '0x89',
    name: Chain.Polygon,
    ticker: ChainTicker.MATIC,
  },
  [Chain.Solana]: {
    cmcId: 5426,
    decimals: 9,
    id: 'Solana_mainnet-beta',
    name: Chain.Solana,
    ticker: ChainTicker.SOL,
  },
  [Chain.THORChain]: {
    cmcId: 4157,
    decimals: 8,
    id: 'Thorchain_1',
    name: Chain.THORChain,
    ticker: ChainTicker.THOR,
  },
}
