import { Chain } from '@core/chain/Chain'
import keyMirror from 'keymirror'

export enum ChainTicker {
  BTC = 'BTC',
  DOGE = 'DOGE',
  LTC = 'LTC',
  BCH = 'BCH',
  ETH = 'ETH',
  AVAX = 'AVAX',
  BNB = 'BNB',
  GAIA = 'GAIA',
  THOR = 'RUNE',
  BSC = 'BSC',
  BASE = 'BASE',
  SOL = 'SOL',
  CRO = 'CRO',
  DYDX = 'DYDX',
  DASH = 'DASH',
  ATOM = 'ATOM',
  KUJI = 'KUJI',
  CACAO = 'CACAO',
  OSMO = 'OSMO',
  MATIC = 'MATIC',
}

export enum CosmosMsgType {
  MSG_SEND = 'cosmos-sdk/MsgSend',
}

export enum Currency {
  AUD = 'AUD',
  CAD = 'CAD',
  CNY = 'CNY',
  EUR = 'EUR',
  GBP = 'GBP',
  JPY = 'JPY',
  RUB = 'RUB',
  SEK = 'SEK',
  SGD = 'SGD',
  USD = 'USD',
}

export enum EventMethod {
  ACCOUNTS_CHANGED = 'accountsChanged',
  CHAIN_CHANGED = 'chainChanged',
  CONNECT = 'connect',
  DISCONNECT = 'diconnect',
  ERROR = 'ERROR',
  MESSAGE = 'MESSAGE',
  NETWORK_CHANGED = 'networkChanged',
}

export enum Instance {
  ACCOUNTS = 'accounts',
  TRANSACTION = 'transaction',
  VAULT = 'vault',
  VAULTS = 'vaults',
}

export enum Language {
  CROATIA = 'hr',
  DUTCH = 'nl',
  ENGLISH = 'en',
  GERMAN = 'de',
  ITALIAN = 'it',
  RUSSIAN = 'ru',
  PORTUGUESE = 'pt',
  SPANISH = 'es',
}

export enum MessageKey {
  BITCOIN_REQUEST = 'bitcoin',
  BITCOIN_CASH_REQUEST = 'bitcoincash',
  COSMOS_REQUEST = 'cosmos',
  DASH_REQUEST = 'dash',
  DOGECOIN_REQUEST = 'dogecoin',
  ETHEREUM_REQUEST = 'ethereum',
  LITECOIN_REQUEST = 'litecoin',
  MAYA_REQUEST = 'maya',
  SOLANA_REQUEST = 'solana',
  THOR_REQUEST = 'thor',
  PRIORITY = 'priority',
  VAULT = 'vault',
  VAULTS = 'vaults',
}

export enum RequestMethod {
  CHAIN_ID = 'chain_id',
  DEPOSIT = 'deposit',
  DEPOSIT_TRANSACTION = 'deposit_transaction',
  ETH_ACCOUNTS = 'eth_accounts',
  ETH_BLOB_BASE_FEE = 'eth_blobBaseFee',
  ETH_BLOCK_NUMBER = 'eth_blockNumber',
  ETH_CALL = 'eth_call',
  ETH_CHAIN_ID = 'eth_chainId',
  ETH_COINBASE = 'eth_coinbase',
  ETH_DECRYPT = 'eth_decrypt',
  ETH_ESTIMATE_GAS = 'eth_estimateGas',
  ETH_FEE_HISTORY = 'eth_feeHistory',
  ETH_GAS_PRICE = 'eth_gasPrice',
  ETH_GET_BALANCE = 'eth_getBalance',
  ETH_GET_BLOCK_BY_HASH = 'eth_getBlockByHash',
  ETH_GET_BLOCK_BY_NUMBER = 'eth_getBlockByNumber',
  ETH_GET_BLOCK_RECEIPTS = 'eth_getBlockReceipts',
  ETH_GET_BLOCK_TRANSACTION_COUNT_BY_HASH = 'eth_getBlockTransactionCountByHash',
  ETH_GET_BLOCK_TRANSACTION_COUNT_BY_NUMBER = 'eth_getBlockTransactionCountByNumber',
  ETH_GET_CODE = 'eth_getCode',
  ETH_GET_ENCRYPTION_PUBLIC_KEY = 'eth_getEncryptionPublicKey',
  ETH_GET_FILTER_CHANGES = 'eth_getFilterChanges',
  ETH_GET_FILTER_LOGS = 'eth_getFilterLogs',
  ETH_GET_LOGS = 'eth_getLogs',
  ETH_GET_PROOF = 'eth_getProof',
  ETH_GET_STORAGEAT = 'eth_getStorageAt',
  ETH_GET_TRANSACTION_BY_BLOCK_HASH_AND_INDEX = 'eth_getTransactionByBlockHashAndIndex',
  ETH_GET_TRANSACTION_BY_BLOCK_NUMBER_AND_INDEX = 'eth_getTransactionByBlockNumberAndIndex',
  ETH_GET_TRANSACTION_BY_HASH = 'eth_getTransactionByHash',
  ETH_GET_TRANSACTION_COUNT = 'eth_getTransactionCount',
  ETH_GET_TRANSACTION_RECEIPT = 'eth_getTransactionReceipt',
  ETH_GET_UNCLE_COUNT_BY_BLOCK_HASH = 'eth_getUncleCountByBlockHash',
  ETH_GET_UNCLE_COUNT_BY_BLOCK_NUMBER = 'eth_getUncleCountByBlockNumber',
  ETH_MAX_PRIORITY_FEE_PER_GAS = 'eth_maxPriorityFeePerGas',
  ETH_NEW_BLOCK_FILTER = 'eth_newBlockFilter',
  ETH_NEW_FILTER = 'eth_newFilter',
  ETH_NEW_PENDING_TRANSACTION_FILTER = 'eth_newPendingTransactionFilter',
  ETH_REQUEST_ACCOUNTS = 'eth_requestAccounts',
  ETH_SEND_RAW_TRANSACTION = 'eth_sendRawTransaction',
  ETH_SEND_TRANSACTION = 'eth_sendTransaction',
  ETH_SIGN = 'eth_sign',
  ETH_SIGN_TYPED_DATA_V4 = 'eth_signTypedData_v4',
  ETH_SUBSCRIBE = 'eth_subscribe',
  ETH_SYNCING = 'eth_syncing',
  ETH_UNINSTALL_FILTER = 'eth_uninstallFilter',
  ETH_UNSUBSCRIBE = 'eth_unsubscribe',
  GET_ACCOUNTS = 'get_accounts',
  GET_TRANSACTION_BY_HASH = 'get_transaction_by_hash',
  GET_UNSPENT_UTXOS = 'get_unspent_utxos',
  NET_VERSION = 'net_version',
  PERSONAL_SIGN = 'personal_sign',
  REQUEST_ACCOUNTS = 'request_accounts',
  REQUEST_ACCOUNTS_AND_KEYS = 'request_accounts_and_keys',
  SEND_TRANSACTION = 'send_transaction',
  SIGN_MESSAGE = 'sign_message',
  SIGN_PSBT = 'sign_psbt',
  SIGN_TRANSACTION = 'sign_transaction',
  TRANSFER = 'transfer',
  WALLET_ADD_CHAIN = 'wallet_add_chain',
  WALLET_ADD_ETHEREUM_CHAIN = 'wallet_addEthereumChain',
  WALLET_GET_PERMISSIONS = 'wallet_getPermissions',
  WALLET_REGISTER_ONBOARDING = 'wallet_registerOnboarding',
  WALLET_REQUEST_PERMISSIONS = 'wallet_requestPermissions',
  WALLET_REVOKE_PERMISSIONS = 'wallet_revokePermissions',
  WALLET_SWITCH_ETHEREUM_CHAIN = 'wallet_switchEthereumChain',
  WALLET_SCAN_QR_CODE = 'wallet_scanQRCode',
  WALLET_SWITCH_CHAIN = 'wallet_switch_chain',
  WALLET_WATCH_ASSET = 'wallet_watchAsset',
  WEB3_CLIENT_VERSION = 'web3_clientVersion',
}

export enum SenderKey {
  PAGE = 'page',
  RELAY = 'relay',
}

export enum TssKeysignType {
  ECDSA = 'ECDSA',
  EdDSA = 'EdDSA',
}

export const currencyName: Record<Currency, string> = {
  [Currency.AUD]: 'Australian Dollar',
  [Currency.CAD]: 'Canadian Dollar',
  [Currency.CNY]: 'Chinese Yuan',
  [Currency.EUR]: 'European Euro',
  [Currency.GBP]: 'British Pound',
  [Currency.JPY]: 'Japanese Yen',
  [Currency.RUB]: 'Russian Ruble',
  [Currency.SEK]: 'Swedish Krona',
  [Currency.SGD]: 'Singapore Dollar',
  [Currency.USD]: 'United States Dollar',
}

export const currencySymbol: Record<Currency, string> = {
  [Currency.AUD]: 'A$',
  [Currency.CAD]: 'C$',
  [Currency.CNY]: '¥',
  [Currency.EUR]: '€',
  [Currency.GBP]: '£',
  [Currency.JPY]: '¥',
  [Currency.RUB]: '₽',
  [Currency.SEK]: 'kr',
  [Currency.SGD]: 'S$',
  [Currency.USD]: '$',
}

export const errorKey = keyMirror({
  FAIL_TO_GET_ACCOUNTS: true,
  FAIL_TO_GET_ADDRESS: true,
  FAIL_TO_GET_VAULT: true,
  FAIL_TO_GET_VAULTS: true,
  FAIL_TO_GET_TRANSACTION: true,
  FAIL_TO_INIT_WASM: true,
  INVALID_CHAIN: true,
  INVALID_EXTENSION: true,
  INVALID_FILE: true,
  INVALID_QRCODE: true,
  INVALID_VAULT: true,
})

export const explorerUrl: Record<Chain, string> = {
  [Chain.Arbitrum]: 'https://arbiscan.io',
  [Chain.Avalanche]: 'https://snowtrace.io',
  [Chain.Base]: 'https://basescan.org',
  [Chain.Bitcoin]: 'https://blockchair.com/bitcoin',
  [Chain.BitcoinCash]: 'https://blockchair.com/bitcoin-cash',
  [Chain.Blast]: 'https://blastscan.io',
  [Chain.BSC]: 'https://bscscan.com',
  [Chain.CronosChain]: 'https://cronoscan.com',
  [Chain.Dash]: 'https://blockchair.com/dash',
  [Chain.Dogecoin]: 'https://blockchair.com/dogecoin',
  [Chain.Dydx]: 'https://www.mintscan.io/dydx',
  [Chain.Ethereum]: 'https://etherscan.io',
  [Chain.Cosmos]: 'https://www.mintscan.io/cosmos',
  [Chain.Kujira]: 'https://finder.kujira.network',
  [Chain.Litecoin]: 'https://blockchair.com/litecoin',
  [Chain.MayaChain]: 'https://www.mayascan.org',
  [Chain.Optimism]: 'https://optimistic.etherscan.io',
  [Chain.Osmosis]: 'https://www.mintscan.io/osmosis',
  [Chain.Polkadot]: 'https://polkadot.subscan.io/account',
  [Chain.Polygon]: 'https://polygonscan.com',
  [Chain.Solana]: 'https://solscan.io',
  [Chain.Sui]: '',
  [Chain.Terra]: '',
  [Chain.TerraClassic]: '',
  [Chain.THORChain]: 'https://thorchain.net',
  [Chain.Ton]: 'https://tonscan.org/',
  [Chain.Ripple]: '',
  [Chain.Zksync]: 'https://explorer.zksync.io',
  [Chain.Noble]: '',
  [Chain.Akash]: '',
}

export const languageName: Record<Language, string> = {
  [Language.CROATIA]: 'Hrvatski',
  [Language.DUTCH]: 'Dutch',
  [Language.ENGLISH]: 'English',
  [Language.GERMAN]: 'Deutsch',
  [Language.ITALIAN]: 'Italiano',
  [Language.PORTUGUESE]: 'Português',
  [Language.RUSSIAN]: 'Русский',
  [Language.SPANISH]: 'Espanol',
}

export const requestAuth: Record<RequestMethod, boolean> = {
  [RequestMethod.CHAIN_ID]: false,
  [RequestMethod.DEPOSIT]: true,
  [RequestMethod.DEPOSIT_TRANSACTION]: true,
  [RequestMethod.ETH_ACCOUNTS]: true,
  [RequestMethod.ETH_BLOB_BASE_FEE]: true,
  [RequestMethod.ETH_BLOCK_NUMBER]: true,
  [RequestMethod.ETH_CALL]: true,
  [RequestMethod.ETH_CHAIN_ID]: false,
  [RequestMethod.ETH_COINBASE]: true,
  [RequestMethod.ETH_DECRYPT]: true,
  [RequestMethod.ETH_ESTIMATE_GAS]: true,
  [RequestMethod.ETH_FEE_HISTORY]: true,
  [RequestMethod.ETH_GAS_PRICE]: true,
  [RequestMethod.ETH_GET_BALANCE]: true,
  [RequestMethod.ETH_GET_BLOCK_BY_HASH]: true,
  [RequestMethod.ETH_GET_BLOCK_BY_NUMBER]: true,
  [RequestMethod.ETH_GET_BLOCK_RECEIPTS]: true,
  [RequestMethod.ETH_GET_BLOCK_TRANSACTION_COUNT_BY_HASH]: true,
  [RequestMethod.ETH_GET_BLOCK_TRANSACTION_COUNT_BY_NUMBER]: true,
  [RequestMethod.ETH_GET_CODE]: true,
  [RequestMethod.ETH_GET_ENCRYPTION_PUBLIC_KEY]: true,
  [RequestMethod.ETH_GET_FILTER_CHANGES]: true,
  [RequestMethod.ETH_GET_FILTER_LOGS]: true,
  [RequestMethod.ETH_GET_LOGS]: true,
  [RequestMethod.ETH_GET_PROOF]: true,
  [RequestMethod.ETH_GET_STORAGEAT]: true,
  [RequestMethod.ETH_GET_TRANSACTION_BY_BLOCK_HASH_AND_INDEX]: true,
  [RequestMethod.ETH_GET_TRANSACTION_BY_BLOCK_NUMBER_AND_INDEX]: true,
  [RequestMethod.ETH_GET_TRANSACTION_BY_HASH]: true,
  [RequestMethod.ETH_GET_TRANSACTION_COUNT]: true,
  [RequestMethod.ETH_GET_TRANSACTION_RECEIPT]: true,
  [RequestMethod.ETH_GET_UNCLE_COUNT_BY_BLOCK_HASH]: true,
  [RequestMethod.ETH_GET_UNCLE_COUNT_BY_BLOCK_NUMBER]: true,
  [RequestMethod.ETH_MAX_PRIORITY_FEE_PER_GAS]: true,
  [RequestMethod.ETH_NEW_BLOCK_FILTER]: true,
  [RequestMethod.ETH_NEW_FILTER]: true,
  [RequestMethod.ETH_NEW_PENDING_TRANSACTION_FILTER]: true,
  [RequestMethod.ETH_REQUEST_ACCOUNTS]: false,
  [RequestMethod.ETH_SEND_RAW_TRANSACTION]: true,
  [RequestMethod.ETH_SEND_TRANSACTION]: true,
  [RequestMethod.ETH_SIGN]: true,
  [RequestMethod.ETH_SIGN_TYPED_DATA_V4]: true,
  [RequestMethod.ETH_SUBSCRIBE]: true,
  [RequestMethod.ETH_SYNCING]: true,
  [RequestMethod.ETH_UNINSTALL_FILTER]: true,
  [RequestMethod.ETH_UNSUBSCRIBE]: true,
  [RequestMethod.GET_ACCOUNTS]: false,
  [RequestMethod.GET_TRANSACTION_BY_HASH]: true,
  [RequestMethod.GET_UNSPENT_UTXOS]: true,
  [RequestMethod.NET_VERSION]: true,
  [RequestMethod.PERSONAL_SIGN]: true,
  [RequestMethod.REQUEST_ACCOUNTS]: false,
  [RequestMethod.REQUEST_ACCOUNTS_AND_KEYS]: true,
  [RequestMethod.SEND_TRANSACTION]: true,
  [RequestMethod.SIGN_MESSAGE]: true,
  [RequestMethod.SIGN_PSBT]: true,
  [RequestMethod.SIGN_TRANSACTION]: true,
  [RequestMethod.TRANSFER]: true,
  [RequestMethod.WALLET_ADD_CHAIN]: true,
  [RequestMethod.WALLET_ADD_ETHEREUM_CHAIN]: true,
  [RequestMethod.WALLET_GET_PERMISSIONS]: true,
  [RequestMethod.WALLET_REGISTER_ONBOARDING]: true,
  [RequestMethod.WALLET_REQUEST_PERMISSIONS]: true,
  [RequestMethod.WALLET_REVOKE_PERMISSIONS]: true,
  [RequestMethod.WALLET_SWITCH_ETHEREUM_CHAIN]: true,
  [RequestMethod.WALLET_SCAN_QR_CODE]: true,
  [RequestMethod.WALLET_SWITCH_CHAIN]: true,
  [RequestMethod.WALLET_WATCH_ASSET]: true,
  [RequestMethod.WEB3_CLIENT_VERSION]: true,
}

export const rpcUrl: Record<Chain, string> = {
  [Chain.Arbitrum]: 'https://api.vultisig.com/arb/',
  [Chain.Avalanche]: 'https://api.vultisig.com/avax/',
  [Chain.Base]: 'https://api.vultisig.com/base/',
  [Chain.Bitcoin]: '',
  [Chain.BitcoinCash]: '',
  [Chain.Blast]: 'https://api.vultisig.com/blast/',
  [Chain.BSC]: 'https://api.vultisig.com/bnb/',
  [Chain.CronosChain]: 'https://cronos-evm-rpc.publicnode.com',
  [Chain.Dash]: '',
  [Chain.Dogecoin]: '',
  [Chain.Dydx]: 'https://dydx-rpc.publicnode.com',
  [Chain.Ethereum]: 'https://api.vultisig.com/eth/',
  [Chain.Cosmos]: 'https://cosmos-rpc.publicnode.com',
  [Chain.Kujira]: 'https://kujira-rpc.publicnode.com',
  [Chain.Litecoin]: '',
  [Chain.MayaChain]: '',
  [Chain.Optimism]: 'https://api.vultisig.com/opt/',
  [Chain.Osmosis]: 'https://osmosis-rpc.publicnode.com',
  [Chain.Polkadot]: '',
  [Chain.Polygon]: 'https://api.vultisig.com/polygon/',
  [Chain.Solana]: 'https://solana-rpc.publicnode.com',
  [Chain.Sui]: '',
  [Chain.Terra]: '',
  [Chain.TerraClassic]: '',
  [Chain.THORChain]: 'https://rpc.ninerealms.com/',
  [Chain.Ton]: '',
  [Chain.Ripple]: 'https://rpc.ninerealms.com/',
  [Chain.Zksync]: 'https://api.vultisig.com/zksync/',
  [Chain.Noble]: '',
  [Chain.Akash]: '',
}

export const storageKey = keyMirror({
  CURRENCY: true,
  LANGUAGE: true,
  VAULTS: true,
})

export const supportedChains: Record<Chain, boolean> = {
  [Chain.Arbitrum]: true,
  [Chain.Avalanche]: true,
  [Chain.Base]: true,
  [Chain.Bitcoin]: true,
  [Chain.BitcoinCash]: true,
  [Chain.Blast]: true,
  [Chain.BSC]: true,
  [Chain.CronosChain]: true,
  [Chain.Dogecoin]: true,
  [Chain.Dash]: true,
  [Chain.Dydx]: true,
  [Chain.Ethereum]: true,
  [Chain.Cosmos]: true,
  [Chain.Kujira]: true,
  [Chain.Litecoin]: true,
  [Chain.MayaChain]: true,
  [Chain.Optimism]: true,
  [Chain.Osmosis]: true,
  [Chain.Polygon]: true,
  [Chain.Solana]: true,
  [Chain.THORChain]: true,
  [Chain.Zksync]: false,
  [Chain.Terra]: false,
  [Chain.TerraClassic]: false,
  [Chain.Noble]: false,
  [Chain.Akash]: false,
  [Chain.Sui]: false,
  [Chain.Polkadot]: false,
  [Chain.Ton]: false,
  [Chain.Ripple]: false,
}

export const isSupportedChain = (chain?: Chain): boolean => {
  return chain ? supportedChains[chain] : false
}
