import keyMirror from "keymirror";

export default keyMirror({
  // A
  ACTIVE: true,
  ADD_NEW_VAULT: true,
  ADD_VAULT_QRCODE: true,
  ADDRESS:true,
  AMOUNT: true,
  // B
  // C
  CANCEL: true,
  CHOOSE_VAULT: true,
  CLOSE: true,
  CONTINE_IN_NEW_WINDOW: true,
  CONNECT: true,
  CONNECT_WITH_VULTISIG: true,
  CONNECTED_DAPPS: true,
  COPY_TX: true,
  CURRENCY: true,
  CURRENT_NETWORK: true,
  // D
  REMOVE_VAULT: true,
  DONE: true,
  DROP_FILE_HERE: true,
  DROP_FILE_HERE_OR: true,
  // E
  ERROR: true,
  // F
  FAQ: true,
  FAST_SIGN: true,
  FUNCTION_SIGNATURE: true,
  FUNCTION_INPUTS: true,
  FIND_YOUR_QRCODE: true,
  FROM: true,
  // G
  GET_VAULT_FAILED: true,
  GET_VAULT_FAILED_DESCRIPTION: true,
  // H
  // I
  IMPORT_FAILED: true,
  IMPORT_SUCCESSED: true,
  IMPORT_VAULT: true,
  // J
  // K
  // L
  LANGUAGE: true,
  // M
  MEMO: true,
  MESSAGE: true,
  // N
  NAME: true,
  NETWORK_FEE: true,
  NO_CONNECTED_APP: true,
  // O
  OPEN_DESKTOP_APP: true,
  OTHER: true,
  OTHER_VAULTS: true,
  // P
  // Q
  // R
  REALOAD_MESSAGE: true,
  REMOVING_VAULT_WARNING: true,
  RENAME_VAULT: true,
  RETRY_ERROR:true,
  // S
  SAVE: true,
  SCAN_QR_WITH_DEVICE: true,
  SCAN_FIRST: true,
  SELECT_A_VAULT: true,
  SETTINGS: true,
  SIGN: true,
  SIGNATURE: true,
  SIGNING: true,
  SIGNING_ERROR: true,
  SIGNING_TIMEOUT_DESCRIPTION: true,
  SIGN_TRANSACTION: true,
  START: true,
  SUCCESSFUL_COPY_LINK: true,
  SUCCESSFUL_COPY_TEXT: true,
  // T
  TO: true,
  TIMEOUT_ERROR: true,
  TRANSACTION: true,
  TRANSACTION_DETAILS: true,
  TRANSACTION_SUCCESSFUL: true,
  // U
  UNLINK: true,
  UNSUCCESSFUL_COPY_LINK: true,
  UNSUCCESSFUL_COPY_TEXT: true,
  UPLOAD_IT: true,
  // V
  VAULT_SETTINGS: true,
  VERIFY_SEND: true,
  VIEW_TX: true,
  VIEW_IN_AIRDROP: true,
  VULT_TOKEN: true,
  VULTISIG: true,
  VULTISIG_CONNECT: true,
  VULTISIG_SLOGAN: true,
  PRIORITIZE_VULTICONNECT: true,
  PRIORITIZE_VULTICONNECT_HINT: true,
  // W
  // Y
  // Z
});
