// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['storage']['Store']['Close']();
}

export function DeleteAddressBookItem(arg1) {
  return window['go']['storage']['Store']['DeleteAddressBookItem'](arg1);
}

export function DeleteCoin(arg1, arg2) {
  return window['go']['storage']['Store']['DeleteCoin'](arg1, arg2);
}

export function DeleteVault(arg1) {
  return window['go']['storage']['Store']['DeleteVault'](arg1);
}

export function DeleteVaultFolder(arg1) {
  return window['go']['storage']['Store']['DeleteVaultFolder'](arg1);
}

export function GetAddressBookItems(arg1) {
  return window['go']['storage']['Store']['GetAddressBookItems'](arg1);
}

export function GetAllAddressBookItems() {
  return window['go']['storage']['Store']['GetAllAddressBookItems']();
}

export function GetCoins(arg1) {
  return window['go']['storage']['Store']['GetCoins'](arg1);
}

export function GetVault(arg1) {
  return window['go']['storage']['Store']['GetVault'](arg1);
}

export function GetVaultFolder(arg1) {
  return window['go']['storage']['Store']['GetVaultFolder'](arg1);
}

export function GetVaultFolders() {
  return window['go']['storage']['Store']['GetVaultFolders']();
}

export function GetVaults() {
  return window['go']['storage']['Store']['GetVaults']();
}

export function Migrate() {
  return window['go']['storage']['Store']['Migrate']();
}

export function SaveAddressBookItem(arg1) {
  return window['go']['storage']['Store']['SaveAddressBookItem'](arg1);
}

export function SaveCoin(arg1, arg2) {
  return window['go']['storage']['Store']['SaveCoin'](arg1, arg2);
}

export function SaveCoins(arg1, arg2) {
  return window['go']['storage']['Store']['SaveCoins'](arg1, arg2);
}

export function SaveVault(arg1) {
  return window['go']['storage']['Store']['SaveVault'](arg1);
}

export function SaveVaultFolder(arg1) {
  return window['go']['storage']['Store']['SaveVaultFolder'](arg1);
}

export function UpdateAddressBookItem(arg1) {
  return window['go']['storage']['Store']['UpdateAddressBookItem'](arg1);
}

export function UpdateVaultFolder(arg1) {
  return window['go']['storage']['Store']['UpdateVaultFolder'](arg1);
}

export function UpdateVaultFolderID(arg1, arg2) {
  return window['go']['storage']['Store']['UpdateVaultFolderID'](arg1, arg2);
}

export function UpdateVaultFolderName(arg1, arg2) {
  return window['go']['storage']['Store']['UpdateVaultFolderName'](arg1, arg2);
}

export function UpdateVaultFolderOrder(arg1, arg2) {
  return window['go']['storage']['Store']['UpdateVaultFolderOrder'](arg1, arg2);
}

export function UpdateVaultIsBackedUp(arg1, arg2) {
  return window['go']['storage']['Store']['UpdateVaultIsBackedUp'](arg1, arg2);
}

export function UpdateVaultName(arg1, arg2) {
  return window['go']['storage']['Store']['UpdateVaultName'](arg1, arg2);
}

export function UpdateVaultOrder(arg1, arg2) {
  return window['go']['storage']['Store']['UpdateVaultOrder'](arg1, arg2);
}
