// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['storage']['Store']['Close']();
}

export function DeleteAddressBookItem(arg1) {
  return window['go']['storage']['Store']['DeleteAddressBookItem'](arg1);
}

export function DeleteCoin(arg1, arg2) {
  return window['go']['storage']['Store']['DeleteCoin'](arg1, arg2);
}

export function DeleteVault(arg1) {
  return window['go']['storage']['Store']['DeleteVault'](arg1);
}

export function DeleteVaultFolder(arg1) {
  return window['go']['storage']['Store']['DeleteVaultFolder'](arg1);
}

export function GetAddressBookItem(arg1) {
  return window['go']['storage']['Store']['GetAddressBookItem'](arg1);
}

export function GetAllAddressBookItems() {
  return window['go']['storage']['Store']['GetAllAddressBookItems']();
}

export function GetCoins() {
  return window['go']['storage']['Store']['GetCoins']();
}

export function GetVault(arg1) {
  return window['go']['storage']['Store']['GetVault'](arg1);
}

export function GetVaultFolder(arg1) {
  return window['go']['storage']['Store']['GetVaultFolder'](arg1);
}

export function GetVaultFolders() {
  return window['go']['storage']['Store']['GetVaultFolders']();
}

export function GetVaults() {
  return window['go']['storage']['Store']['GetVaults']();
}

export function Migrate() {
  return window['go']['storage']['Store']['Migrate']();
}

export function SaveAddressBookItem(arg1) {
  return window['go']['storage']['Store']['SaveAddressBookItem'](arg1);
}

export function SaveCoin(arg1, arg2) {
  return window['go']['storage']['Store']['SaveCoin'](arg1, arg2);
}

export function SaveCoins(arg1, arg2) {
  return window['go']['storage']['Store']['SaveCoins'](arg1, arg2);
}

export function SaveVault(arg1) {
  return window['go']['storage']['Store']['SaveVault'](arg1);
}

export function SaveVaultFolder(arg1) {
  return window['go']['storage']['Store']['SaveVaultFolder'](arg1);
}

export function UpdateAddressBookItem(arg1) {
  return window['go']['storage']['Store']['UpdateAddressBookItem'](arg1);
}
