/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_signsession_free: (a: number, b: number) => void;
export const signsession_new: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
export const signsession_setup: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number, number];
export const signsession_setupMessageHash: (a: number, b: number) => [number, number];
export const signsession_setupKeyId: (a: number, b: number) => [number, number];
export const signsession_outputMessage: (a: number) => number;
export const signsession_inputMessage: (a: number, b: number, c: number) => number;
export const signsession_finish: (a: number) => [number, number, number, number];
export const __wbg_keygensession_free: (a: number, b: number) => void;
export const keygensession_new: (a: number, b: number, c: number, d: number) => [number, number, number];
export const keygensession_setup: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const keygensession_setupKeyId: (a: number, b: number) => [number, number];
export const keygensession_outputMessage: (a: number) => number;
export const keygensession_inputMessage: (a: number, b: number, c: number) => number;
export const keygensession_finish: (a: number) => [number, number, number];
export const __wbg_keyshare_free: (a: number, b: number) => void;
export const keyshare_publicKey: (a: number) => [number, number];
export const keyshare_keyId: (a: number) => [number, number];
export const keyshare_toBytes: (a: number) => [number, number];
export const keyshare_fromBytes: (a: any) => [number, number, number];
export const __wbg_message_free: (a: number, b: number) => void;
export const message_body: (a: number) => [number, number];
export const message_receivers: (a: number) => [number, number];
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_start: () => void;
