// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file vultisig/keygen/v1/single_keygen_type.proto (package vultisig.keygen.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from '@bufbuild/protobuf/codegenv2'
import { enumDesc, fileDesc } from '@bufbuild/protobuf/codegenv2'

/**
 * Describes the file vultisig/keygen/v1/single_keygen_type.proto.
 */
export const file_vultisig_keygen_v1_single_keygen_type: GenFile =
  /*@__PURE__*/
  fileDesc(
    'Cit2dWx0aXNpZy9rZXlnZW4vdjEvc2luZ2xlX2tleWdlbl90eXBlLnByb3RvEhJ2dWx0aXNpZy5rZXlnZW4udjEqMAoQU2luZ2xlS2V5Z2VuVHlwZRIcChhTSU5HTEVfS0VZR0VOX1RZUEVfTUxEU0EQAEJSChJ2dWx0aXNpZy5rZXlnZW4udjFaN2dpdGh1Yi5jb20vdnVsdGlzaWcvY29tbW9uZGF0YS9nby92dWx0aXNpZy9rZXlnZW4vdjE7djG6AgJWU2IGcHJvdG8z'
  )

/**
 * buf:lint:ignore ENUM_ZERO_VALUE_SUFFIX
 *
 * @generated from enum vultisig.keygen.v1.SingleKeygenType
 */
export enum SingleKeygenType {
  /**
   * @generated from enum value: SINGLE_KEYGEN_TYPE_MLDSA = 0;
   */
  MLDSA = 0,
}

/**
 * Describes the enum vultisig.keygen.v1.SingleKeygenType.
 */
export const SingleKeygenTypeSchema: GenEnum<SingleKeygenType> =
  /*@__PURE__*/
  enumDesc(file_vultisig_keygen_v1_single_keygen_type, 0)
