// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateInstallMarker():Promise<void>;

export function GetAppDataDir():Promise<string>;

export function IsFreshInstall():Promise<boolean>;
