// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdvertiseMediator(arg1:string):Promise<void>;

export function DiscoveryService(arg1:string):Promise<string>;

export function StartServer():Promise<void>;

export function StopAdvertiseMediator():Promise<void>;

export function StopServer():Promise<void>;
