// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdvertiseMediator(arg1) {
  return window['go']['mediator']['Server']['AdvertiseMediator'](arg1);
}

export function DiscoveryService(arg1) {
  return window['go']['mediator']['Server']['DiscoveryService'](arg1);
}

export function StartServer() {
  return window['go']['mediator']['Server']['StartServer']();
}

export function StopAdvertiseMediator() {
  return window['go']['mediator']['Server']['StopAdvertiseMediator']();
}

export function StopServer() {
  return window['go']['mediator']['Server']['StopServer']();
}
