// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {agent} from '../models';
import {context} from '../models';
import {storage} from '../models';
import {backend} from '../models';

export function CancelRequest():Promise<void>;

export function CheckServices(arg1:string):Promise<agent.ServiceStatus>;

export function CreateConversation(arg1:string):Promise<string>;

export function DeleteConversation(arg1:string,arg2:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function ExecuteAction(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetAuthToken(arg1:context.Context,arg2:storage.Vault,arg3:string):Promise<string>;

export function GetAuthTokenInfo(arg1:string):Promise<agent.AuthTokenInfo>;

export function GetCachedAuthToken(arg1:string):Promise<string>;

export function GetConversation(arg1:string,arg2:string):Promise<backend.ConversationWithMessages>;

export function GetConversations(arg1:string):Promise<Array<backend.Conversation>>;

export function GetVerifierSignInStatus(arg1:string):Promise<boolean>;

export function InvalidateAuthToken(arg1:string):Promise<void>;

export function PreloadContext(arg1:string):Promise<void>;

export function ProvideBalance(arg1:string):Promise<void>;

export function ProvideChainAddress(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:string,arg7:string,arg8:string):Promise<void>;

export function ProvideConfirmation(arg1:boolean):Promise<void>;

export function ProvideDKLSReshare(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<void>;

export function ProvideDKLSSignature(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function ProvidePassword(arg1:string):Promise<void>;

export function ProvidePortfolio(arg1:string):Promise<void>;

export function ProvideToolResult(arg1:string):Promise<void>;

export function SelectSuggestion(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SendMessage(arg1:string,arg2:string):Promise<string>;

export function SendMessageToConversation(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SignIn(arg1:string,arg2:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
