// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelRequest() {
  return window['go']['agent']['AgentService']['CancelRequest']();
}

export function ClearHistory(arg1) {
  return window['go']['agent']['AgentService']['ClearHistory'](arg1);
}

export function DeleteConversation(arg1) {
  return window['go']['agent']['AgentService']['DeleteConversation'](arg1);
}

export function ExportConversation(arg1) {
  return window['go']['agent']['AgentService']['ExportConversation'](arg1);
}

export function GenerateConversationStarters(arg1) {
  return window['go']['agent']['AgentService']['GenerateConversationStarters'](arg1);
}

export function GetApiKeyStatus() {
  return window['go']['agent']['AgentService']['GetApiKeyStatus']();
}

export function GetAuthToken(arg1, arg2, arg3) {
  return window['go']['agent']['AgentService']['GetAuthToken'](arg1, arg2, arg3);
}

export function GetCachedAuthToken(arg1) {
  return window['go']['agent']['AgentService']['GetCachedAuthToken'](arg1);
}

export function GetConversation(arg1) {
  return window['go']['agent']['AgentService']['GetConversation'](arg1);
}

export function GetConversationStarters(arg1) {
  return window['go']['agent']['AgentService']['GetConversationStarters'](arg1);
}

export function GetConversations(arg1) {
  return window['go']['agent']['AgentService']['GetConversations'](arg1);
}

export function GetVerifierSignInStatus(arg1) {
  return window['go']['agent']['AgentService']['GetVerifierSignInStatus'](arg1);
}

export function NewConversation(arg1, arg2) {
  return window['go']['agent']['AgentService']['NewConversation'](arg1, arg2);
}

export function ProvideConfirmation(arg1) {
  return window['go']['agent']['AgentService']['ProvideConfirmation'](arg1);
}

export function ProvidePassword(arg1) {
  return window['go']['agent']['AgentService']['ProvidePassword'](arg1);
}

export function SendMessage(arg1, arg2) {
  return window['go']['agent']['AgentService']['SendMessage'](arg1, arg2);
}

export function SetActiveConversation(arg1) {
  return window['go']['agent']['AgentService']['SetActiveConversation'](arg1);
}

export function SetApiKey(arg1) {
  return window['go']['agent']['AgentService']['SetApiKey'](arg1);
}

export function SignIn(arg1, arg2) {
  return window['go']['agent']['AgentService']['SignIn'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['agent']['AgentService']['Startup'](arg1);
}

export function UpdateConversationName(arg1, arg2) {
  return window['go']['agent']['AgentService']['UpdateConversationName'](arg1, arg2);
}
