// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {storage} from '../models';
import {agent} from '../models';

export function CancelRequest():Promise<void>;

export function ClearHistory(arg1:string):Promise<void>;

export function DeleteConversation(arg1:string):Promise<void>;

export function ExportConversation(arg1:string):Promise<string>;

export function GenerateConversationStarters(arg1:string):Promise<void>;

export function GetApiKeyStatus():Promise<boolean>;

export function GetAuthToken(arg1:context.Context,arg2:storage.Vault,arg3:string):Promise<string>;

export function GetCachedAuthToken(arg1:string):Promise<string>;

export function GetConversation(arg1:string):Promise<agent.Conversation>;

export function GetConversationStarters(arg1:string):Promise<Array<string>>;

export function GetConversations(arg1:string):Promise<Array<agent.Conversation>>;

export function GetVerifierSignInStatus(arg1:string):Promise<boolean>;

export function InvalidateAuthToken(arg1:string):Promise<void>;

export function NewConversation(arg1:string,arg2:string):Promise<string>;

export function ProvideConfirmation(arg1:boolean):Promise<void>;

export function ProvideDKLSReshare(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<void>;

export function ProvideDKLSSignature(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function ProvidePassword(arg1:string):Promise<void>;

export function SendMessage(arg1:string,arg2:string):Promise<string>;

export function SetActiveConversation(arg1:string):Promise<void>;

export function SetApiKey(arg1:string):Promise<void>;

export function SignIn(arg1:string,arg2:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateConversationName(arg1:string,arg2:string):Promise<void>;
