// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelRequest() {
  return window['go']['agent']['AgentService']['CancelRequest']();
}

export function CheckServices(arg1) {
  return window['go']['agent']['AgentService']['CheckServices'](arg1);
}

export function CreateConversation(arg1) {
  return window['go']['agent']['AgentService']['CreateConversation'](arg1);
}

export function DeleteConversation(arg1, arg2) {
  return window['go']['agent']['AgentService']['DeleteConversation'](arg1, arg2);
}

export function Disconnect(arg1) {
  return window['go']['agent']['AgentService']['Disconnect'](arg1);
}

export function ExecuteAction(arg1, arg2, arg3) {
  return window['go']['agent']['AgentService']['ExecuteAction'](arg1, arg2, arg3);
}

export function GetAuthToken(arg1, arg2, arg3) {
  return window['go']['agent']['AgentService']['GetAuthToken'](arg1, arg2, arg3);
}

export function GetAuthTokenInfo(arg1) {
  return window['go']['agent']['AgentService']['GetAuthTokenInfo'](arg1);
}

export function GetCachedAuthToken(arg1) {
  return window['go']['agent']['AgentService']['GetCachedAuthToken'](arg1);
}

export function GetConversation(arg1, arg2) {
  return window['go']['agent']['AgentService']['GetConversation'](arg1, arg2);
}

export function GetConversations(arg1) {
  return window['go']['agent']['AgentService']['GetConversations'](arg1);
}

export function GetVerifierSignInStatus(arg1) {
  return window['go']['agent']['AgentService']['GetVerifierSignInStatus'](arg1);
}

export function InvalidateAuthToken(arg1) {
  return window['go']['agent']['AgentService']['InvalidateAuthToken'](arg1);
}

export function PreloadContext(arg1) {
  return window['go']['agent']['AgentService']['PreloadContext'](arg1);
}

export function ProvideBalance(arg1) {
  return window['go']['agent']['AgentService']['ProvideBalance'](arg1);
}

export function ProvideChainAddress(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['agent']['AgentService']['ProvideChainAddress'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function ProvideConfirmation(arg1) {
  return window['go']['agent']['AgentService']['ProvideConfirmation'](arg1);
}

export function ProvideDKLSReshare(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['agent']['AgentService']['ProvideDKLSReshare'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ProvideDKLSSignature(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['agent']['AgentService']['ProvideDKLSSignature'](arg1, arg2, arg3, arg4, arg5);
}

export function ProvidePassword(arg1) {
  return window['go']['agent']['AgentService']['ProvidePassword'](arg1);
}

export function ProvidePortfolio(arg1) {
  return window['go']['agent']['AgentService']['ProvidePortfolio'](arg1);
}

export function ProvideToolResult(arg1) {
  return window['go']['agent']['AgentService']['ProvideToolResult'](arg1);
}

export function SelectSuggestion(arg1, arg2, arg3) {
  return window['go']['agent']['AgentService']['SelectSuggestion'](arg1, arg2, arg3);
}

export function SendMessage(arg1, arg2) {
  return window['go']['agent']['AgentService']['SendMessage'](arg1, arg2);
}

export function SendMessageToConversation(arg1, arg2, arg3) {
  return window['go']['agent']['AgentService']['SendMessageToConversation'](arg1, arg2, arg3);
}

export function SignIn(arg1, arg2) {
  return window['go']['agent']['AgentService']['SignIn'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['agent']['AgentService']['Startup'](arg1);
}
