// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file vultisig/vault/v1/vault.proto (package vultisig.vault.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { LibType } from "../../keygen/v1/lib_type_message_pb";
import { file_vultisig_keygen_v1_lib_type_message } from "../../keygen/v1/lib_type_message_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file vultisig/vault/v1/vault.proto.
 */
export const file_vultisig_vault_v1_vault: GenFile = /*@__PURE__*/
  fileDesc("Ch12dWx0aXNpZy92YXVsdC92MS92YXVsdC5wcm90bxIRdnVsdGlzaWcudmF1bHQudjEi9QMKBVZhdWx0EgwKBG5hbWUYASABKAkSGAoQcHVibGljX2tleV9lY2RzYRgCIAEoCRIYChBwdWJsaWNfa2V5X2VkZHNhGAMgASgJEg8KB3NpZ25lcnMYBCADKAkSLgoKY3JlYXRlZF9hdBgFIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASFgoOaGV4X2NoYWluX2NvZGUYBiABKAkSNQoKa2V5X3NoYXJlcxgHIAMoCzIhLnZ1bHRpc2lnLnZhdWx0LnYxLlZhdWx0LktleVNoYXJlEhYKDmxvY2FsX3BhcnR5X2lkGAggASgJEhYKDnJlc2hhcmVfcHJlZml4GAkgASgJEi0KCGxpYl90eXBlGAogASgOMhsudnVsdGlzaWcua2V5Z2VuLnYxLkxpYlR5cGUSQgoRY2hhaW5fcHVibGljX2tleXMYCyADKAsyJy52dWx0aXNpZy52YXVsdC52MS5WYXVsdC5DaGFpblB1YmxpY0tleRowCghLZXlTaGFyZRISCgpwdWJsaWNfa2V5GAEgASgJEhAKCGtleXNoYXJlGAIgASgJGkUKDkNoYWluUHVibGljS2V5EhIKCnB1YmxpY19rZXkYASABKAkSDQoFY2hhaW4YAiABKAkSEAoIaXNfZWRkc2EYAyABKAhCUAoRdnVsdGlzaWcudmF1bHQudjFaNmdpdGh1Yi5jb20vdnVsdGlzaWcvY29tbW9uZGF0YS9nby92dWx0aXNpZy92YXVsdC92MTt2MboCAlZTYgZwcm90bzM", [file_google_protobuf_timestamp, file_vultisig_keygen_v1_lib_type_message]);

/**
 * @generated from message vultisig.vault.v1.Vault
 */
export type Vault = Message<"vultisig.vault.v1.Vault"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string public_key_ecdsa = 2;
   */
  publicKeyEcdsa: string;

  /**
   * @generated from field: string public_key_eddsa = 3;
   */
  publicKeyEddsa: string;

  /**
   * @generated from field: repeated string signers = 4;
   */
  signers: string[];

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 5;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: string hex_chain_code = 6;
   */
  hexChainCode: string;

  /**
   * @generated from field: repeated vultisig.vault.v1.Vault.KeyShare key_shares = 7;
   */
  keyShares: Vault_KeyShare[];

  /**
   * @generated from field: string local_party_id = 8;
   */
  localPartyId: string;

  /**
   * @generated from field: string reshare_prefix = 9;
   */
  resharePrefix: string;

  /**
   * @generated from field: vultisig.keygen.v1.LibType lib_type = 10;
   */
  libType: LibType;

  /**
   * @generated from field: repeated vultisig.vault.v1.Vault.ChainPublicKey chain_public_keys = 11;
   */
  chainPublicKeys: Vault_ChainPublicKey[];
};

/**
 * Describes the message vultisig.vault.v1.Vault.
 * Use `create(VaultSchema)` to create a new message.
 */
export const VaultSchema: GenMessage<Vault> = /*@__PURE__*/
  messageDesc(file_vultisig_vault_v1_vault, 0);

/**
 * @generated from message vultisig.vault.v1.Vault.KeyShare
 */
export type Vault_KeyShare = Message<"vultisig.vault.v1.Vault.KeyShare"> & {
  /**
   * @generated from field: string public_key = 1;
   */
  publicKey: string;

  /**
   * @generated from field: string keyshare = 2;
   */
  keyshare: string;
};

/**
 * Describes the message vultisig.vault.v1.Vault.KeyShare.
 * Use `create(Vault_KeyShareSchema)` to create a new message.
 */
export const Vault_KeyShareSchema: GenMessage<Vault_KeyShare> = /*@__PURE__*/
  messageDesc(file_vultisig_vault_v1_vault, 0, 0);

/**
 * @generated from message vultisig.vault.v1.Vault.ChainPublicKey
 */
export type Vault_ChainPublicKey = Message<"vultisig.vault.v1.Vault.ChainPublicKey"> & {
  /**
   * @generated from field: string public_key = 1;
   */
  publicKey: string;

  /**
   * @generated from field: string chain = 2;
   */
  chain: string;

  /**
   * @generated from field: bool is_eddsa = 3;
   */
  isEddsa: boolean;
};

/**
 * Describes the message vultisig.vault.v1.Vault.ChainPublicKey.
 * Use `create(Vault_ChainPublicKeySchema)` to create a new message.
 */
export const Vault_ChainPublicKeySchema: GenMessage<Vault_ChainPublicKey> = /*@__PURE__*/
  messageDesc(file_vultisig_vault_v1_vault, 0, 1);

