// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {utils} from '../models';

export function Post(arg1:utils.HttpPostRequest):Promise<utils.HttpPostResponse>;
