export const midgardBaseUrl = 'https://midgard.thorchain.network/v2'
export const mayaMidgardBaseUrl = 'https://midgard.mayachain.info/v2'
export const thornodeBaseUrl = 'https://thornode.thorchain.network/thorchain'
export const mayanodeBaseUrl = 'https://mayanode.mayachain.info/mayachain'
export const rujiStakeApiUrl = 'https://api.vultisig.com/ruji/api/graphql'
