// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Fetch(arg1:string):Promise<any>;

export function Post(arg1:string,arg2:any):Promise<any>;
