// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Fetch(arg1) {
  return window['go']['utils']['GoHttp']['Fetch'](arg1);
}

export function Post(arg1, arg2) {
  return window['go']['utils']['GoHttp']['Post'](arg1, arg2);
}
