import { ChainObjRef } from "../types";
import { ChainKey } from "./chainKeys";

export const CHAINS: ChainObjRef = {
  [ChainKey.ARBITRUM]: {
    cmcId: 1027,
    decimals: 18,
    id: "0xa4b1",
    name: ChainKey.ARBITRUM,
    ticker: "ETH",
  },
  [ChainKey.AVALANCHE]: {
    cmcId: 5805,
    decimals: 18,
    id: "0xa86a",
    name: ChainKey.AVALANCHE,
    ticker: "AVAX",
  },
  [ChainKey.BASE]: {
    cmcId: 1027,
    decimals: 18,
    id: "0x2105",
    name: ChainKey.BASE,
    ticker: "ETH",
  },
  [ChainKey.BITCOIN]: {
    cmcId: 1,
    decimals: 8,
    id: "0x1f96",
    name: ChainKey.BITCOIN,
    ticker: "BTC",
  },
  [ChainKey.BITCOINCASH]: {
    cmcId: 1831,
    decimals: 8,
    id: "0x2710",
    name: ChainKey.BITCOINCASH,
    ticker: "BCH",
  },
  [ChainKey.BLAST]: {
    cmcId: 1027,
    decimals: 18,
    id: "0x13e31",
    name: ChainKey.BLAST,
    ticker: "ETH",
  },
  [ChainKey.BSCCHAIN]: {
    cmcId: 1839,
    decimals: 18,
    id: "0x38",
    name: ChainKey.BSCCHAIN,
    ticker: "BNB",
  },
  [ChainKey.CRONOSCHAIN]: {
    cmcId: 3635,
    decimals: 18,
    id: "0x19",
    name: ChainKey.CRONOSCHAIN,
    ticker: "CRO",
  },
  [ChainKey.DOGECOIN]: {
    cmcId: 74,
    decimals: 8,
    id: "0x7d0",
    name: ChainKey.DOGECOIN,
    ticker: "DOGE",
  },
  [ChainKey.DYDX]: {
    cmcId: 28324,
    decimals: 18,
    id: "dydx-1",
    name: ChainKey.DYDX,
    ticker: "DYDX",
  },
  [ChainKey.ETHEREUM]: {
    cmcId: 1027,
    decimals: 18,
    id: "0x1",
    name: ChainKey.ETHEREUM,
    ticker: "ETH",
  },
  [ChainKey.DASH]: {
    cmcId: 131,
    decimals: 8,
    id: "Dash_dash",
    name: ChainKey.DASH,
    ticker: "DASH",
  },
  [ChainKey.GAIACHAIN]: {
    cmcId: 3794,
    decimals: 6,
    id: "cosmoshub-4",
    name: ChainKey.GAIACHAIN,
    ticker: "ATOM",
  },
  [ChainKey.KUJIRA]: {
    cmcId: 15185,
    decimals: 6,
    id: "kaiyo-1",
    name: ChainKey.KUJIRA,
    ticker: "KUJI",
  },
  [ChainKey.LITECOIN]: {
    cmcId: 2,
    decimals: 8,
    id: "Litecoin_litecoin",
    name: ChainKey.LITECOIN,
    ticker: "LTC",
  },
  [ChainKey.MAYACHAIN]: {
    cmcId: 23534,
    decimals: 10,
    id: "MayaChain-1",
    name: ChainKey.MAYACHAIN,
    ticker: "CACAO",
  },
  [ChainKey.OPTIMISM]: {
    cmcId: 1027,
    decimals: 18,
    id: "Optimism_optimism",
    name: ChainKey.OPTIMISM,
    ticker: "ETH",
  },
  [ChainKey.OSMOSIS]: {
    cmcId: 12220,
    decimals: 6,
    id: "osmosis-1",
    name: ChainKey.OSMOSIS,
    ticker: "OSMO",
  },
  [ChainKey.POLYGON]: {
    cmcId: 3890,
    decimals: 18,
    id: "0x89",
    name: ChainKey.POLYGON,
    ticker: "MATIC",
  },
  [ChainKey.SOLANA]: {
    cmcId: 5426,
    decimals: 9,
    id: "Solana_mainnet-beta",
    name: ChainKey.SOLANA,
    ticker: "SOL",
  },
  [ChainKey.THORCHAIN]: {
    cmcId: 4157,
    decimals: 8,
    id: "Thorchain_1",
    name: ChainKey.THORCHAIN,
    ticker: "RUNE",
  },
};
