// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';
import {tss} from '../models';
import {context} from '../models';

export function GetLocalUIEcdsa(arg1:string):Promise<string>;

export function GetLocalUIEdDSA(arg1:string):Promise<string>;

export function Keysign(arg1:storage.Vault,arg2:Array<string>,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<Array<tss.KeysignResponse>>;

export function Reshare(arg1:storage.Vault,arg2:string,arg3:string,arg4:string):Promise<storage.Vault>;

export function StartKeygen(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<storage.Vault>;

export function Startup(arg1:context.Context):Promise<void>;
