// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {tss} from '../models';
import {storage} from '../models';

export function GetDerivedPubKey(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function KeysignECDSA(arg1:tss.KeysignRequest):Promise<tss.KeysignResponse>;

export function StartKeygen(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<storage.Vault>;
