// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDerivedPubKey(arg1, arg2, arg3, arg4) {
  return window['go']['tss']['TssService']['GetDerivedPubKey'](arg1, arg2, arg3, arg4);
}

export function KeysignECDSA(arg1) {
  return window['go']['tss']['TssService']['KeysignECDSA'](arg1);
}

export function StartKeygen(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['tss']['TssService']['StartKeygen'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function Startup(arg1) {
  return window['go']['tss']['TssService']['Startup'](arg1);
}
