// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {tss} from '../models';

export function GetDerivedPubKey(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function GetLocalState(arg1:string):Promise<string>;

export function KeysignECDSA(arg1:tss.KeysignRequest):Promise<tss.KeysignResponse>;

export function SaveLocalState(arg1:string,arg2:string):Promise<void>;

export function Send(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StartTssInstance():Promise<void>;
