// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLocalState(arg1) {
  return window['go']['tss']['TssService']['GetLocalState'](arg1);
}

export function SaveLocalState(arg1, arg2) {
  return window['go']['tss']['TssService']['SaveLocalState'](arg1, arg2);
}

export function Send(arg1, arg2, arg3) {
  return window['go']['tss']['TssService']['Send'](arg1, arg2, arg3);
}

export function StartTssInstance() {
  return window['go']['tss']['TssService']['StartTssInstance']();
}
