// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {frontend} from '../models';

export function SaveFile(arg1:string,arg2:string,arg3:Array<frontend.FileFilter>):Promise<string>;
