// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SaveFile(arg1: string, arg2: string): Promise<string>;

export function SaveFileBkp(arg1: string, arg2: string): Promise<string>;
