// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateInstallMarker() {
  return window['go']['main']['InstallMarkerService']['CreateInstallMarker']();
}

export function GetAppDataDir() {
  return window['go']['main']['InstallMarkerService']['GetAppDataDir']();
}

export function IsFreshInstall() {
  return window['go']['main']['InstallMarkerService']['IsFreshInstall']();
}
