// @generated by protoc-gen-es v2.7.0 with parameter "target=ts,json_types=true"
// @generated from file constraint.proto (package types, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file constraint.proto.
 */
export const file_constraint: GenFile = /*@__PURE__*/
  fileDesc("ChBjb25zdHJhaW50LnByb3RvEgV0eXBlcyLrAQoKQ29uc3RyYWludBIjCgR0eXBlGAEgASgOMhUudHlwZXMuQ29uc3RyYWludFR5cGUSFQoLZml4ZWRfdmFsdWUYAiABKAlIABITCgltYXhfdmFsdWUYAyABKAlIABITCgltaW5fdmFsdWUYBCABKAlIABI0ChRtYWdpY19jb25zdGFudF92YWx1ZRgFIAEoDjIULnR5cGVzLk1hZ2ljQ29uc3RhbnRIABIWCg5kZW5vbWluYXRlZF9pbhgGIAEoCRIOCgZwZXJpb2QYByABKAkSEAoIcmVxdWlyZWQYCCABKAhCBwoFdmFsdWUquwEKDkNvbnN0cmFpbnRUeXBlEh8KG0NPTlNUUkFJTlRfVFlQRV9VTlNQRUNJRklFRBAAEhkKFUNPTlNUUkFJTlRfVFlQRV9GSVhFRBABEhcKE0NPTlNUUkFJTlRfVFlQRV9NQVgQAhIXChNDT05TVFJBSU5UX1RZUEVfTUlOEAMSIgoeQ09OU1RSQUlOVF9UWVBFX01BR0lDX0NPTlNUQU5UEAQSFwoTQ09OU1RSQUlOVF9UWVBFX0FOWRAFKjcKDU1hZ2ljQ29uc3RhbnQSDwoLVU5TUEVDSUZJRUQQABIVChFWVUxUSVNJR19UUkVBU1VSWRABQiNaIWdpdGh1Yi5jb20vdnVsdGlzaWcvcmVjaXBlcy90eXBlc2IGcHJvdG8z");

/**
 * Constraint defines restrictions on a parameter
 *
 * @generated from message types.Constraint
 */
export type Constraint = Message<"types.Constraint"> & {
  /**
   * Type of constraint (fixed, max, min, etc.)
   *
   * @generated from field: types.ConstraintType type = 1;
   */
  type: ConstraintType;

  /**
   * Value of the constraint (depends on Type)
   *
   * @generated from oneof types.Constraint.value
   */
  value: {
    /**
     * @generated from field: string fixed_value = 2;
     */
    value: string;
    case: "fixedValue";
  } | {
    /**
     * @generated from field: string max_value = 3;
     */
    value: string;
    case: "maxValue";
  } | {
    /**
     * @generated from field: string min_value = 4;
     */
    value: string;
    case: "minValue";
  } | {
    /**
     * @generated from field: types.MagicConstant magic_constant_value = 5;
     */
    value: MagicConstant;
    case: "magicConstantValue";
  } | { case: undefined; value?: undefined };

  /**
   * Additional metadata for the constraint
   *
   * @generated from field: string denominated_in = 6;
   */
  denominatedIn: string;

  /**
   * @generated from field: string period = 7;
   */
  period: string;

  /**
   * @generated from field: bool required = 8;
   */
  required: boolean;
};

/**
 * Constraint defines restrictions on a parameter
 *
 * @generated from message types.Constraint
 */
export type ConstraintJson = {
  /**
   * Type of constraint (fixed, max, min, etc.)
   *
   * @generated from field: types.ConstraintType type = 1;
   */
  type?: ConstraintTypeJson;

  /**
   * @generated from field: string fixed_value = 2;
   */
  fixedValue?: string;

  /**
   * @generated from field: string max_value = 3;
   */
  maxValue?: string;

  /**
   * @generated from field: string min_value = 4;
   */
  minValue?: string;

  /**
   * @generated from field: types.MagicConstant magic_constant_value = 5;
   */
  magicConstantValue?: MagicConstantJson;

  /**
   * Additional metadata for the constraint
   *
   * @generated from field: string denominated_in = 6;
   */
  denominatedIn?: string;

  /**
   * @generated from field: string period = 7;
   */
  period?: string;

  /**
   * @generated from field: bool required = 8;
   */
  required?: boolean;
};

/**
 * Describes the message types.Constraint.
 * Use `create(ConstraintSchema)` to create a new message.
 */
export const ConstraintSchema: GenMessage<Constraint, {jsonType: ConstraintJson}> = /*@__PURE__*/
  messageDesc(file_constraint, 0);

/**
 * ConstraintType defines the type of constraint
 *
 * @generated from enum types.ConstraintType
 */
export enum ConstraintType {
  /**
   * @generated from enum value: CONSTRAINT_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: CONSTRAINT_TYPE_FIXED = 1;
   */
  FIXED = 1,

  /**
   * @generated from enum value: CONSTRAINT_TYPE_MAX = 2;
   */
  MAX = 2,

  /**
   * @generated from enum value: CONSTRAINT_TYPE_MIN = 3;
   */
  MIN = 3,

  /**
   * @generated from enum value: CONSTRAINT_TYPE_MAGIC_CONSTANT = 4;
   */
  MAGIC_CONSTANT = 4,

  /**
   * @generated from enum value: CONSTRAINT_TYPE_ANY = 5;
   */
  ANY = 5,
}

/**
 * ConstraintType defines the type of constraint
 *
 * @generated from enum types.ConstraintType
 */
export type ConstraintTypeJson = "CONSTRAINT_TYPE_UNSPECIFIED" | "CONSTRAINT_TYPE_FIXED" | "CONSTRAINT_TYPE_MAX" | "CONSTRAINT_TYPE_MIN" | "CONSTRAINT_TYPE_MAGIC_CONSTANT" | "CONSTRAINT_TYPE_ANY";

/**
 * Describes the enum types.ConstraintType.
 */
export const ConstraintTypeSchema: GenEnum<ConstraintType, ConstraintTypeJson> = /*@__PURE__*/
  enumDesc(file_constraint, 0);

/**
 * @generated from enum types.MagicConstant
 */
export enum MagicConstant {
  /**
   * @generated from enum value: UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: VULTISIG_TREASURY = 1;
   */
  VULTISIG_TREASURY = 1,
}

/**
 * @generated from enum types.MagicConstant
 */
export type MagicConstantJson = "UNSPECIFIED" | "VULTISIG_TREASURY";

/**
 * Describes the enum types.MagicConstant.
 */
export const MagicConstantSchema: GenEnum<MagicConstant, MagicConstantJson> = /*@__PURE__*/
  enumDesc(file_constraint, 1);

