// @generated by protoc-gen-es v2.10.1 with parameter "target=ts,json_types=true"
// @generated from file recipe_specification.proto (package types, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ConstraintType, ConstraintTypeJson } from "./constraint_pb";
import { file_constraint } from "./constraint_pb";
import type { StructJson } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_struct } from "@bufbuild/protobuf/wkt";
import type { ResourcePath, ResourcePathJson } from "./resource_pb";
import { file_resource } from "./resource_pb";
import type { TargetType, TargetTypeJson } from "./rule_pb";
import { file_rule } from "./rule_pb";
import type { JsonObject, Message } from "@bufbuild/protobuf";

/**
 * Describes the file recipe_specification.proto.
 */
export const file_recipe_specification: GenFile = /*@__PURE__*/
  fileDesc("ChpyZWNpcGVfc3BlY2lmaWNhdGlvbi5wcm90bxIFdHlwZXMirQIKDFJlY2lwZVNjaGVtYRIPCgd2ZXJzaW9uGAEgASgFEhEKCXBsdWdpbl9pZBgDIAEoCRITCgtwbHVnaW5fbmFtZRgEIAEoCRIWCg5wbHVnaW5fdmVyc2lvbhgFIAEoBRIzChNzdXBwb3J0ZWRfcmVzb3VyY2VzGAYgAygLMhYudHlwZXMuUmVzb3VyY2VQYXR0ZXJuEi8KDHJlcXVpcmVtZW50cxgIIAEoCzIZLnR5cGVzLlBsdWdpblJlcXVpcmVtZW50cxIuCg1jb25maWd1cmF0aW9uGAkgASgLMhcuZ29vZ2xlLnByb3RvYnVmLlN0cnVjdBI2ChVjb25maWd1cmF0aW9uX2V4YW1wbGUYCiADKAsyFy5nb29nbGUucHJvdG9idWYuU3RydWN0IrgBCg9SZXNvdXJjZVBhdHRlcm4SKgoNcmVzb3VyY2VfcGF0aBgBIAEoCzITLnR5cGVzLlJlc291cmNlUGF0aBJEChZwYXJhbWV0ZXJfY2FwYWJpbGl0aWVzGAIgAygLMiQudHlwZXMuUGFyYW1ldGVyQ29uc3RyYWludENhcGFiaWxpdHkSEAoIcmVxdWlyZWQYAyABKAgSIQoGdGFyZ2V0GAQgASgOMhEudHlwZXMuVGFyZ2V0VHlwZSJ5Ch1QYXJhbWV0ZXJDb25zdHJhaW50Q2FwYWJpbGl0eRIWCg5wYXJhbWV0ZXJfbmFtZRgBIAEoCRIuCg9zdXBwb3J0ZWRfdHlwZXMYAiABKA4yFS50eXBlcy5Db25zdHJhaW50VHlwZRIQCghyZXF1aXJlZBgDIAEoCCJMChJQbHVnaW5SZXF1aXJlbWVudHMSHAoUbWluX3Z1bHRpc2lnX3ZlcnNpb24YASABKAUSGAoQc3VwcG9ydGVkX2NoYWlucxgCIAMoCUIjWiFnaXRodWIuY29tL3Z1bHRpc2lnL3JlY2lwZXMvdHlwZXNiBnByb3RvMw", [file_constraint, file_google_protobuf_struct, file_resource, file_rule]);

/**
 * RecipeSchema defines what types of recipes/policies a plugin can handle
 * This is used for UI filtering and policy validation
 *
 * @generated from message types.RecipeSchema
 */
export type RecipeSchema = Message<"types.RecipeSchema"> & {
  /**
   * Schema version for future compatibility
   *
   * @generated from field: int32 version = 1;
   */
  version: number;

  /**
   * Plugin identification
   *
   * @generated from field: string plugin_id = 3;
   */
  pluginId: string;

  /**
   * @generated from field: string plugin_name = 4;
   */
  pluginName: string;

  /**
   * @generated from field: int32 plugin_version = 5;
   */
  pluginVersion: number;

  /**
   * What resources this plugin can handle with their parameter constraints
   *
   * @generated from field: repeated types.ResourcePattern supported_resources = 6;
   */
  supportedResources: ResourcePattern[];

  /**
   * Plugin requirements
   *
   * @generated from field: types.PluginRequirements requirements = 8;
   */
  requirements?: PluginRequirements;

  /**
   * Plugin configuration
   *
   * @generated from field: google.protobuf.Struct configuration = 9;
   */
  configuration?: JsonObject;

  /**
   * Plugin configuration_example
   *
   * @generated from field: repeated google.protobuf.Struct configuration_example = 10;
   */
  configurationExample: JsonObject[];
};

/**
 * RecipeSchema defines what types of recipes/policies a plugin can handle
 * This is used for UI filtering and policy validation
 *
 * @generated from message types.RecipeSchema
 */
export type RecipeSchemaJson = {
  /**
   * Schema version for future compatibility
   *
   * @generated from field: int32 version = 1;
   */
  version?: number;

  /**
   * Plugin identification
   *
   * @generated from field: string plugin_id = 3;
   */
  pluginId?: string;

  /**
   * @generated from field: string plugin_name = 4;
   */
  pluginName?: string;

  /**
   * @generated from field: int32 plugin_version = 5;
   */
  pluginVersion?: number;

  /**
   * What resources this plugin can handle with their parameter constraints
   *
   * @generated from field: repeated types.ResourcePattern supported_resources = 6;
   */
  supportedResources?: ResourcePatternJson[];

  /**
   * Plugin requirements
   *
   * @generated from field: types.PluginRequirements requirements = 8;
   */
  requirements?: PluginRequirementsJson;

  /**
   * Plugin configuration
   *
   * @generated from field: google.protobuf.Struct configuration = 9;
   */
  configuration?: StructJson;

  /**
   * Plugin configuration_example
   *
   * @generated from field: repeated google.protobuf.Struct configuration_example = 10;
   */
  configurationExample?: StructJson[];
};

/**
 * Describes the message types.RecipeSchema.
 * Use `create(RecipeSchemaSchema)` to create a new message.
 */
export const RecipeSchemaSchema: GenMessage<RecipeSchema, {jsonType: RecipeSchemaJson}> = /*@__PURE__*/
  messageDesc(file_recipe_specification, 0);

/**
 * ResourcePattern defines a specific resource and what constraints its parameters support
 *
 * @generated from message types.ResourcePattern
 */
export type ResourcePattern = Message<"types.ResourcePattern"> & {
  /**
   * Specific resource (e.g., ethereum.eth.transfer)
   *
   * @generated from field: types.ResourcePath resource_path = 1;
   */
  resourcePath?: ResourcePath;

  /**
   * What constraint types each parameter of this resource supports
   *
   * @generated from field: repeated types.ParameterConstraintCapability parameter_capabilities = 2;
   */
  parameterCapabilities: ParameterConstraintCapability[];

  /**
   * Whether this resource is required by the plugin
   *
   * @generated from field: bool required = 3;
   */
  required: boolean;

  /**
   * Tx 'to'
   *
   * @generated from field: types.TargetType target = 4;
   */
  target: TargetType;
};

/**
 * ResourcePattern defines a specific resource and what constraints its parameters support
 *
 * @generated from message types.ResourcePattern
 */
export type ResourcePatternJson = {
  /**
   * Specific resource (e.g., ethereum.eth.transfer)
   *
   * @generated from field: types.ResourcePath resource_path = 1;
   */
  resourcePath?: ResourcePathJson;

  /**
   * What constraint types each parameter of this resource supports
   *
   * @generated from field: repeated types.ParameterConstraintCapability parameter_capabilities = 2;
   */
  parameterCapabilities?: ParameterConstraintCapabilityJson[];

  /**
   * Whether this resource is required by the plugin
   *
   * @generated from field: bool required = 3;
   */
  required?: boolean;

  /**
   * Tx 'to'
   *
   * @generated from field: types.TargetType target = 4;
   */
  target?: TargetTypeJson;
};

/**
 * Describes the message types.ResourcePattern.
 * Use `create(ResourcePatternSchema)` to create a new message.
 */
export const ResourcePatternSchema: GenMessage<ResourcePattern, {jsonType: ResourcePatternJson}> = /*@__PURE__*/
  messageDesc(file_recipe_specification, 1);

/**
 * ParameterConstraintCapability defines what constraint types a parameter supports
 *
 * @generated from message types.ParameterConstraintCapability
 */
export type ParameterConstraintCapability = Message<"types.ParameterConstraintCapability"> & {
  /**
   * Parameter name (e.g., "recipient", "amount")
   *
   * @generated from field: string parameter_name = 1;
   */
  parameterName: string;

  /**
   * Supported constraint types for this parameter
   *
   * @generated from field: types.ConstraintType supported_types = 2;
   */
  supportedTypes: ConstraintType;

  /**
   * Whether this parameter must be constrained
   *
   * @generated from field: bool required = 3;
   */
  required: boolean;
};

/**
 * ParameterConstraintCapability defines what constraint types a parameter supports
 *
 * @generated from message types.ParameterConstraintCapability
 */
export type ParameterConstraintCapabilityJson = {
  /**
   * Parameter name (e.g., "recipient", "amount")
   *
   * @generated from field: string parameter_name = 1;
   */
  parameterName?: string;

  /**
   * Supported constraint types for this parameter
   *
   * @generated from field: types.ConstraintType supported_types = 2;
   */
  supportedTypes?: ConstraintTypeJson;

  /**
   * Whether this parameter must be constrained
   *
   * @generated from field: bool required = 3;
   */
  required?: boolean;
};

/**
 * Describes the message types.ParameterConstraintCapability.
 * Use `create(ParameterConstraintCapabilitySchema)` to create a new message.
 */
export const ParameterConstraintCapabilitySchema: GenMessage<ParameterConstraintCapability, {jsonType: ParameterConstraintCapabilityJson}> = /*@__PURE__*/
  messageDesc(file_recipe_specification, 2);

/**
 * PluginRequirements defines what the plugin needs to function
 *
 * @generated from message types.PluginRequirements
 */
export type PluginRequirements = Message<"types.PluginRequirements"> & {
  /**
   * Minimum Vultisig version required
   *
   * @generated from field: int32 min_vultisig_version = 1;
   */
  minVultisigVersion: number;

  /**
   * Supported blockchain networks
   *
   * @generated from field: repeated string supported_chains = 2;
   */
  supportedChains: string[];
};

/**
 * PluginRequirements defines what the plugin needs to function
 *
 * @generated from message types.PluginRequirements
 */
export type PluginRequirementsJson = {
  /**
   * Minimum Vultisig version required
   *
   * @generated from field: int32 min_vultisig_version = 1;
   */
  minVultisigVersion?: number;

  /**
   * Supported blockchain networks
   *
   * @generated from field: repeated string supported_chains = 2;
   */
  supportedChains?: string[];
};

/**
 * Describes the message types.PluginRequirements.
 * Use `create(PluginRequirementsSchema)` to create a new message.
 */
export const PluginRequirementsSchema: GenMessage<PluginRequirements, {jsonType: PluginRequirementsJson}> = /*@__PURE__*/
  messageDesc(file_recipe_specification, 3);

