// @generated by protoc-gen-es v2.8.0 with parameter "target=ts,json_types=true"
// @generated from file resource.proto (package types, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file resource.proto.
 */
export const file_resource: GenFile = /*@__PURE__*/
  fileDesc("Cg5yZXNvdXJjZS5wcm90bxIFdHlwZXMiWAoMUmVzb3VyY2VQYXRoEhAKCGNoYWluX2lkGAEgASgJEhMKC3Byb3RvY29sX2lkGAIgASgJEhMKC2Z1bmN0aW9uX2lkGAMgASgJEgwKBGZ1bGwYBCABKAlCI1ohZ2l0aHViLmNvbS92dWx0aXNpZy9yZWNpcGVzL3R5cGVzYgZwcm90bzM");

/**
 * ResourcePath represents a parsed resource path
 *
 * @generated from message types.ResourcePath
 */
export type ResourcePath = Message<"types.ResourcePath"> & {
  /**
   * ChainID is the blockchain identifier
   *
   * @generated from field: string chain_id = 1;
   */
  chainId: string;

  /**
   * ProtocolID is the protocol identifier
   *
   * @generated from field: string protocol_id = 2;
   */
  protocolId: string;

  /**
   * FunctionID is the function identifier
   *
   * @generated from field: string function_id = 3;
   */
  functionId: string;

  /**
   * Full is the complete resource path
   *
   * @generated from field: string full = 4;
   */
  full: string;
};

/**
 * ResourcePath represents a parsed resource path
 *
 * @generated from message types.ResourcePath
 */
export type ResourcePathJson = {
  /**
   * ChainID is the blockchain identifier
   *
   * @generated from field: string chain_id = 1;
   */
  chainId?: string;

  /**
   * ProtocolID is the protocol identifier
   *
   * @generated from field: string protocol_id = 2;
   */
  protocolId?: string;

  /**
   * FunctionID is the function identifier
   *
   * @generated from field: string function_id = 3;
   */
  functionId?: string;

  /**
   * Full is the complete resource path
   *
   * @generated from field: string full = 4;
   */
  full?: string;
};

/**
 * Describes the message types.ResourcePath.
 * Use `create(ResourcePathSchema)` to create a new message.
 */
export const ResourcePathSchema: GenMessage<ResourcePath, {jsonType: ResourcePathJson}> = /*@__PURE__*/
  messageDesc(file_resource, 0);

