// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,json_types=true"
// @generated from file resource.proto (package types, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file resource.proto.
 */
export const file_resource: GenFile = /*@__PURE__*/
  fileDesc("Cg5yZXNvdXJjZS5wcm90bxIFdHlwZXMiWAoMUmVzb3VyY2VQYXRoEhAKCGNoYWluX2lkGAEgASgJEhMKC3Byb3RvY29sX2lkGAIgASgJEhMKC2Z1bmN0aW9uX2lkGAMgASgJEgwKBGZ1bGwYBCABKAkiPAoKUGVybWlzc2lvbhIKCgJpZBgBIAEoCRINCgVsYWJlbBgCIAEoCRITCgtkZXNjcmlwdGlvbhgDIAEoCUIjWiFnaXRodWIuY29tL3Z1bHRpc2lnL3JlY2lwZXMvdHlwZXNiBnByb3RvMw");

/**
 * ResourcePath represents a parsed resource path
 *
 * @generated from message types.ResourcePath
 */
export type ResourcePath = Message<"types.ResourcePath"> & {
  /**
   * ChainID is the blockchain identifier
   *
   * @generated from field: string chain_id = 1;
   */
  chainId: string;

  /**
   * ProtocolID is the protocol identifier
   *
   * @generated from field: string protocol_id = 2;
   */
  protocolId: string;

  /**
   * FunctionID is the function identifier
   *
   * @generated from field: string function_id = 3;
   */
  functionId: string;

  /**
   * Full is the complete resource path
   *
   * @generated from field: string full = 4;
   */
  full: string;
};

/**
 * ResourcePath represents a parsed resource path
 *
 * @generated from message types.ResourcePath
 */
export type ResourcePathJson = {
  /**
   * ChainID is the blockchain identifier
   *
   * @generated from field: string chain_id = 1;
   */
  chainId?: string;

  /**
   * ProtocolID is the protocol identifier
   *
   * @generated from field: string protocol_id = 2;
   */
  protocolId?: string;

  /**
   * FunctionID is the function identifier
   *
   * @generated from field: string function_id = 3;
   */
  functionId?: string;

  /**
   * Full is the complete resource path
   *
   * @generated from field: string full = 4;
   */
  full?: string;
};

/**
 * Describes the message types.ResourcePath.
 * Use `create(ResourcePathSchema)` to create a new message.
 */
export const ResourcePathSchema: GenMessage<ResourcePath, {jsonType: ResourcePathJson}> = /*@__PURE__*/
  messageDesc(file_resource, 0);

/**
 * Permission represents a user-facing permission for UI display
 *
 * @generated from message types.Permission
 */
export type Permission = Message<"types.Permission"> & {
  /**
   * Unique identifier (e.g., "transaction_signing", "fee_deduction", "balance_visibility")
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Display label (e.g., "Access to transaction signing")
   *
   * @generated from field: string label = 2;
   */
  label: string;

  /**
   * Tooltip text (e.g., "The app can initiate transactions to swap assets in your Vault")
   *
   * @generated from field: string description = 3;
   */
  description: string;
};

/**
 * Permission represents a user-facing permission for UI display
 *
 * @generated from message types.Permission
 */
export type PermissionJson = {
  /**
   * Unique identifier (e.g., "transaction_signing", "fee_deduction", "balance_visibility")
   *
   * @generated from field: string id = 1;
   */
  id?: string;

  /**
   * Display label (e.g., "Access to transaction signing")
   *
   * @generated from field: string label = 2;
   */
  label?: string;

  /**
   * Tooltip text (e.g., "The app can initiate transactions to swap assets in your Vault")
   *
   * @generated from field: string description = 3;
   */
  description?: string;
};

/**
 * Describes the message types.Permission.
 * Use `create(PermissionSchema)` to create a new message.
 */
export const PermissionSchema: GenMessage<Permission, {jsonType: PermissionJson}> = /*@__PURE__*/
  messageDesc(file_resource, 1);

